### ISSUE TITLE
Region Data Changes

### ISSUE THREAD

**Issue by seema84** [NLthijs48/AreaShop#102]
[WorldGuard] Region data changes made in 'world' have been background saved
please fix this
http://forum.enginehub.org/threads/region-data-changes-have-been-background-saved.16346/

**Comment by NLthijs48** [comment]
I guess you don't really understand what this message indicates. First of all, this is not a warning as mentioned by the first poster in the linked thread, but it is a simple information type message. The message simply indicates that region changes have been saved to disk, which is good and what you want. You also get this message if you use the WorldGuard commands ingame, because at some point WorldGuard should save the regions to disk so that after a server restart the changes are saved.

The reason that it might get triggered more often with AreaShop is that AreaShop changes the WorldGuard regions automatically, for example when someone rents a region, or if a rent runs out.

So there is nothing to fix about these messages, I also don't really know why WorldGuard is even printing those to console constantly, they are not useful for the normal plugin user.

Let me know if that clears up what those messages are about and if that what you needed to know.

**Comment by seema84** [comment]
I know what this message is. Im only confused to read in sk forum that these message can remove.
But thanks for your answer i think you can close this issue.

**Comment by NLthijs48** [comment]
They are saying that it can be removed because when you edit the source of the plugin you can do anything you want, so also removing the message from WorldGuard.
