### ISSUE TITLE
region types

### ISSUE THREAD

**Issue by silentspectr** [NLthijs48/AreaShop#109]
Hi i'm making rentable and buyable regions for my server and i was wondering if it is possible to make two kinds of regions. let me explain by an example:

i have hotel rooms for rent, house for sell and shops for sell

i don't want players to be able to rent more than one room or buy more than one house but i need them to be able to buy 1 shop whether or not they own a house or have a room

at the end the result i need is: a region type "shop" and a region type "home" including house and hotel room each type can only have one region at a time per player

i hope you understood what i said =) thanks

**Comment by NLthijs48** [comment]
You should be able to set this up with the `limitGroups` section in the `config.yml` file, check [this page](https://github.com/NLthijs48/AreaShop/wiki/Limitgroups-information-and-examples) for more information and examples about this.

The [Advanced regions setup](https://github.com/NLthijs48/AreaShop/wiki/Advanced-regions-setup) page might also be useful, since the group system is definitely something that you can use for your setup. The group system lets you add all regions of a certain type to a group, and then set settings like price, duration, etc for all of them at once.

Let me know if it worked or if you have any questions.

**Comment by silentspectr** [comment]
AMAZING 
it worked just as expected 
thank you

**Comment by NLthijs48** [comment]
Nice :)

**Comment by silentspectr** [comment]
sorry if i reopen it but i have another question i forgot 
is it possible to use the "as groupadd" command without selecting the region again but using the region name instead?
i tried 'as groupadd <group> <region> but it didn't worked 
thanks

**Comment by NLthijs48** [comment]
The command also has an optional region argument, so yes that is possible:
`/as groupadd <group> [region]` (all commands can be found [here](https://github.com/NLthijs48/AreaShop/wiki/Commands-and-Permissions)).

However if you have a lot of regions then it is easier to simply make a WorldEdit selection that contains all of them, and then use the `/as groupadd` command without a region name, then it will add all regions that it can find inside your selection.

**Comment by silentspectr** [comment]
nice 
the second option is really good for lazy people like me :D 
thank you
