### ISSUE TITLE
error after update to worldedit dev #3409

### ISSUE THREAD

**Issue by frizzbee30** [NLthijs48/AreaShop#111]
Hi, This has started appearing,doesn't seem to affect normal functionality, but not tried setting new shop/rent regions as yet. I think it has coincided with an update to the latest worldedit dev.

http://pastebin.com/TkefmsAa

Thanks

**Comment by frizzbee30** [comment]
Haven't changed any configs etc prior to the error appearing :)

**Comment by NLthijs48** [comment]
This error is not from the WorldGuard/WorldEdit connection, the error is from a region file that cannot be loaded correctly. I suspect that one of the region files is empty, because it says that it cannot find a map at the top level. You could try sorting your region files (at '/plugins/AreaShop/regions') on size to check if any of them are empty. Of course these files should never be empty, so there must have gone something wrong with either AreaShop or the file system.

The latest [dev build](http://ci.frostcast.net/job/AreaShop/) should now print out the name of the region file that could not be loaded correctly, so that should help debugging the problem better.

**Comment by frizzbee30** [comment]
Thats great, thanks! :)
