### ISSUE TITLE
Adding multiple landlords

### ISSUE THREAD

**Issue by Mineville** [NLthijs48/AreaShop#112]
Problem:
On my server there are multiple owners of towns on several worlds. They are able to claim regions and offer them for rent/sell. I would like them to get the money for the rented regions, so they can get money out of their work on their city.

Is there a way you could add the feature, that e.g. the landlord is automatically set when creating a sign? Or that the sign format completely changes (e.g.

Line 1: [asrent]
Line 2: %region%
Line 3: %price% : %time% 
Line 4: %landlord%)

so the landlord is always set by the creator of the sign?

Kind regards

Lukas

**Comment by NLthijs48** [comment]
AreaShop should already do this, if a player has permission to add regions that he is member/owner of, but does NOT have the general `areashop.createrent` or `areashop.createbuy` permission then he is added as landlord. So make sure that this is the case and see if this works correctly. This means that the city owner should place the sign themself, and should already be an owner or member of the WorldGuard region (I assume you already have this, since you mention they can claim regions).

Let me know if that solves your problem.

**Comment by Mineville** [comment]
The city owner has the permissions areashop.createrent.owner, addsign and delsign.
I will take a look if it works and will tell you afterwards.

**Comment by Mineville** [comment]
It works for me now!

I tried to test it with all permissions, so i even had the general permissions with createrent etc.

Thanks for helping me out <3

**Comment by NLthijs48** [comment]
Nice that you got it fixed, after your ticket I also clarified some things on the Commands and Permissions page so that should be helpful for others having issues with this.
