### ISSUE TITLE
rightClickConsole not working for 1.7.10 cauldron

### ISSUE THREAD

**Issue by i9hdkill** [NLthijs48/AreaShop#117]
Hi,
we are using area shop 2.1.1 + wg 6.1 on a 1.7.10 cauldron server (Latest official bps patched build 2xx)

Selling renting is working fine, but today I tried to setup the confirm message on rightclick event, however when I perform a rightclick, I rent the region, no console output.

Config:

http://pastebin.com/GEi1e0JC

To make sure the config is properly working I changed the leftclick to
- 'areashop info regionnnnnn %region%'

(something invalid)

output: command not working.

But seems like the server/plugin doesn't like the rightClickConsole command he just runs the default /as rent command....

Cauldron or 1.7.10 limitation?
No errors in console log

**Comment by NLthijs48** [comment]
I did some testing and can confirm that there are some problems. The issue here is that first the player commands are executed, and after that the console commands. So if the player commands change the state of the region (for rent to rented for example), then the console commands for the new state are executed, instead of the correct ones.

I have fixed this issue for the next version, you can download a [dev build here](http://ci.frostcast.net/job/AreaShop/) if you want to have it fixed immediately. However the reasing that it is still running the renting command directly is because of the fallback system. There is no `rightClickPlayer` section in your config, so then the default setting is used, which is rent the region. To fix this problem you can add the `rightClickPlayer` section to your config, but without any commands listed in it. Then it will not fallback to the default setting anymore. If you do that then the current version of AreaShop should also work fine, so running the dev build is not necessary.

Thank you for reporting this issue, it is very unlikely that I would have found this issue anytime soon myself.

**Comment by i9hdkill** [comment]
Thank you very much for the quick fix!
