### ISSUE TITLE
PLEASE ADD THIS ASAP

### ISSUE THREAD

**Issue by Skyboyfly** [NLthijs48/AreaShop#118]
So could you please add a option where you can add friends to your rent / buy (Or in other words for me, apartment/house.) SO like if a player does 
'/as add <player name>' 
 the player they added could open regular chest (NOT Trapped chest) if the Option in config is set to false for other players to open the chest, cause if it was set to true, of course anyone could open them. Then could you add another cammand:
 '/as add admin <player name>'
Which would let players be able to place blocks like the owner in the shop/and add players to the territory. Although I'm not sure how it would work with multiple homes/rents- Actually you could have it set up to where the owner has to be standing in the territory to add the person to the territory there renting/ bought, for each cammand. Please for the love of god add this... It would be a awesome feature

**Comment by NLthijs48** [comment]
I'm not sure if you know this already, but there is already the `/as addfriend` command. This commands lets players add other players to their regions, and those players can then also build in the region and use it. In the `config.yml` file you can change if the friends are added as owner or member, so you could setup the permissions and flags so that only the region owner can build there, and that friends can only use chests.

Let me know if that already covers the feature that you would like to use.

**Comment by NLthijs48** [comment]
I'm assuming your problem is solved.
