### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by Agazed** [NLthijs48/AreaShop#12]
How do you compile this project?

**Comment by NLthijs48** [comment]
Good question, I will try to make a tutorial for this later this evening. 

Basically: clone the repository to your computer. Then make a project in your IDE and add all source and resource files. After that add the dependencies to the buildpath (Bukkit 1.7.9, Vault 1.4.1, WorldGuard 6.0 [use latest version] and WorldEdit  6.0 [use latest version]). Then use Export -> Jar file, be sure that you have all files selected for export (source folders, plugin.yml, config.yml, default.yml, lang folder).

I'm currently using Java 7 to compile AreaShop so make sure you also have that (8 also works fine as long as the server you want to run it on has 8).

Out of interest: Do you want to compile AreaShop because you made some changes yourself? Or do you want the latest version that is on the master branch?

**Comment by NLthijs48** [comment]
I added some basic instruction for compiling to the readme file. Also added a description of all packages and classes in AreaShop. Will be adding some more things to it later.

Let me know if you successfully compiled AreaShop, then I can close this ticket.

**Comment by Agazed** [comment]
Thank you! I have figured it out.

**Comment by NLthijs48** [comment]
Okey nice, then i will close this ticket.
