### ISSUE TITLE
Door can be opened by anyone

### ISSUE THREAD

**Issue by Dejerne** [NLthijs48/AreaShop#120]
Me and my friend is setting up a big prison server. We only have 1 issue with Areashop. When a person rent a cell, with the door inside of the region, anyone can open the door, but can't build inside the region/cell

**Comment by EvilOlaf** [comment]
Make sure you set your WorldGuard priorities right.

**Comment by Dejerne** [comment]
What u mean with that?

**Comment by Dejerne** [comment]
Can you send a example on how to fix it?

**Comment by EvilOlaf** [comment]
AreaShop is based on WorldGuard regions. If you have multiple regions overlaying each other there could be issues if those regions have the same priority. You can rais the priority of a particular region to make flags set there work.

My guess is that you have one big region and multiple smaller ones for AreaShop. If a player rents one of those and he can't build in it, it is probably because the outer, bigger region does not allow this player to build within it.
So increase the priority of the players region to allow him building. Use the `/rg priority` command for that.

**Comment by Dejerne** [comment]
Its the door that doenst work.

**Comment by EvilOlaf** [comment]
Maybe you set the `use` flag to `true` at your outer region, which allows the use of all elements in inner regions too.

**Comment by Dejerne** [comment]
Nope

**Comment by NLthijs48** [comment]
Change the `flagProfiles` section in the `config.yml` file of AreaShop to the same as listed [here](https://github.com/NLthijs48/AreaShop/blob/master/AreaShop/src/main/resources/config.yml#L251-L278) (these are the new defaults that will be in the next release of AreaShop). This setup will only let the member/owner of the region use blocks in his region, including doors. The `interact` flag is the important one to solve your problem.

Let me know if you got it working.

**Comment by Dejerne** [comment]
Sorry for being so late. Not we cant build in our rented regions

**Comment by NLthijs48** [comment]
I'm assuming this has been fixed.

**Comment by Bassen1244** [comment]
I still not works for me, pllz help if your still there, i can either do so no one can open doors or all people can open doors, i very important for my prison server
