### ISSUE TITLE
Allow renting bought regions

### ISSUE THREAD

**Issue by leNicDev** [NLthijs48/AreaShop#123]
Players who bought a region can rent it. This would require the ability to set the owner of a RentRegion. Would be cool if you can realize it!

**Comment by NLthijs48** [comment]
Do you mean that a player that bought a region can rent it out to other players? Because renting it himself after buying it does not make any sense. You can set players as landlord of a region (`/as setlandlord <player> [region]`), which will let the player get all money made by the region. But switching the region type between buy and rent is not really possible (Unless you want to let the console execute commands that remove a region from AreaShop and then add it again as a different type). For fancy solutions you can use the `eventCommandProfiles` section in the config file, which you can use to execute commands when something happens.

**Comment by NLthijs48** [comment]
Assuming this has been fixed.
