### ISSUE TITLE
Add permission for sign-use

### ISSUE THREAD

**Issue by Androkai** [NLthijs48/AreaShop#129]
I want to give my users the ability to sell there own regions but often someone accidentally sneak + klick the sign and sell his own region (+reset it in my case) so i disabled it for them. I wish for a additional permission to use signs so that they can only sell it via command.

**Comment by EvilOlaf** [comment]
Why not adding kind a confirmation for this case? https://github.com/NLthijs48/AreaShop/issues/50

**Comment by NLthijs48** [comment]
Like @EvilOlaf suggested confirmations would probably be the best thing, the option is still there but at least it is not instant. Another thing you can do is simply remove the shift right click command from the sign by changing the `signProfiles` section in the `config.yml` file.

Separate permissions for clicking signs and commands are quite tough since the only thing the signs currently do is executing a list of commands. So the code that actually handles the command does not know if it is typed or comes from a sign.

Let me know if one of the suggested solutions works for you or if you think that separate permissions would still be needed.

**Comment by Androkai** [comment]
Because the server-team uses the function to easily reset old regions I will use @EvilOlaf`s suggestion. It's a klick more for the staff but this should be acceptable. Thx for the suggestions.

**Comment by EvilOlaf** [comment]
You're welcome
