### ISSUE TITLE
Rental sign doesn't work

### ISSUE THREAD

**Issue by Ulriksebastian** [NLthijs48/AreaShop#132]
When i my make AS rental region, and then try to make the Rent sig, nothing happens.
This is what i write:
[rent]
celle1
1 d
500

Please help if you can. And feel free to ask me about other info.

**Comment by EvilOlaf** [comment]
There is no need to write these signs by yourself. Just use `as addsign` while aiming to an empty sign and let AreaShop create the sign for you.

**Comment by NLthijs48** [comment]
The default tag to write on signs is `[asrent]` since the latest versions, to make sure you are using the correct one check the `config.yml` file, the `signTags` section defines the tags you have to write.

Using the command `/as addsign` as suggested by @EvilOlaf also works though, or if you have a lot of signs to do, then consider using `/as linksigns`.

**Comment by NLthijs48** [comment]
I'm assuming the information above fixed the problem.
