### ISSUE TITLE
Safe location teleport

### ISSUE THREAD

**Issue by morsay** [NLthijs48/AreaShop#145]
Hello, sry for my bad english, its possible to make a minimum height for the safe location ? Coz when a player use the teleport they spawn very deep in little cave.

Thanks

**Comment by NLthijs48** [comment]
You cannot set the minimum height of the teleport, but you can set the initial height. The initial height and the middle of the x and z axis of the region is used as the starting point for the safe teleport. And then it searches around that with an increasing radius to find a safe spot.

By default the initial y position is `bottom`, so that would explain why you get teleported in a cave. If you set `teleportLocationY` in `default.yml` to `middle` then it should be a lot better. If you have regions from the bottom of the world until the top, and the floor is around `y=64`, then it is better to set the location to `64`.

**Comment by NLthijs48** [comment]
I'm assuming that my message above fixed your problem.
