### ISSUE TITLE
People does not have acces to /as addfriend

### ISSUE THREAD

**Issue by majidfan123** [NLthijs48/AreaShop#146]
http://pastebin.com/d6CfkKAc - Group perms
http://pastebin.com/aZa2jCGW - Config

Please help, normal players does not have acces to as addfrriend

**Comment by NLthijs48** [comment]
By default AreaShop already gives everyone the permissions for `/as addfriend`, so unless your permission plugin takes that permission away all players should be able to use the command (check all default permissions [here](https://github.com/NLthijs48/AreaShop/wiki/Commands-and-Permissions)).

I'm not using GroupManager (which I assume your file is from) myself so I'm not totally sure about how that setup works, but it looks like you are not blocking any relevant AreaShop permissions.

Does `/as help` list the addfriend command or not for players? Because if it does list it then it should also be able to execute, if it does not list it then the player has no permission for it 

You can also try using a command of GroupManager to check permissions of a player and check for `areashop.addfriend` and see if GroupManager allows it or not (`manucheckp` seems to be the command to use?).

**Comment by NLthijs48** [comment]
Closing the issue, assuming it has been solved.
