### ISSUE TITLE
Show player name in region info

### ISSUE THREAD

**Issue by ZoefyC** [NLthijs48/AreaShop#149]
Hi,

I was wondering... Is there a way to show the players name instead of the UUID in the worldguard region info (/rg i)? I love the region signs, but I'm using the dynmap worldguard map, too, and this would be super awesome. 
I tried using %player% instead of %uuid%, but this breaks it. 

`[AreaShop] Tried using 'ZoefyC' as uuid for a region member, is your flagProfiles section correct?`

I hope you can help :)
~ Zoe

**Comment by NLthijs48** [comment]
Normally WorldGuard should display the name of the player, also when they are added by UUID. Are you using the latest version of WorldGuard? There might be some cases this does not work though, but since I'm not the developer of WorldGuard I'm not sure about that.

Using `%player%` directly does not work, you need to use `n:%player%` to add a player by name. So you could use that as a workaround, note that if a player changes his name this will only be reflected on signs and the WorldGuard region after a server restart or a login of the player (name changing does not happen often though).

Let me know if that fixes your problem.

**Comment by jewome62** [comment]
I think it's better to add the uuid in region.
Because the player can change this username :D

**Comment by NLthijs48** [comment]
Closing the issue, assuming it has been solved.
