### ISSUE TITLE
Sign breaking

### ISSUE THREAD

**Issue by confuser** [NLthijs48/AreaShop#15]
Breaking a block behind a sign causes the sign to be destroyed.

We're allowing players to customise the look of their shops, and this is causing some bother.

Can there be an option to cancel the BlockPhysicsEvent instead of outputting a warning to the console?

**Comment by NLthijs48** [comment]
I'm aware of this issue, but there are some good reasons that I implemented it like it is currently in AreaShop. 

The first slight problem is that there is no way to know who caused a BlockPhysicsEvent (and it does not even have to be a player), so I can do nothing that is permission based, since there is nobody to check the permission against.

Another problem is that cancelling the BlockPhysicsEvent is not always a proper solution. If for example the sign is attached to sand or gravel, then breaking the block below the sand or gravel would cause them to fall. However if AreaShop would cancel the event then the falling stops, but only until the next gametick. So this situation would cause the BlockPhysicsEvent to be called every gametick (20 times a second) and therefore spam events. There are more situations like this that would cause the cancel to not work properly, and simply cause unnecessary strain for the server.

These are the reasons that I only use the BlockPhysicsEvent to detect sign breakage, and remove them from AreaShop (if I don't do that then next update of the region a floating sign is placed).

I usually place the signs just outside of the area that the player can edit, which solves the situation. However I can imagine that is not always what you want to do. There are a couple of things that could solve this situation, but they are not really perfect and clean solutions. One of them is to simply place a block under/below the sign when it is detected that the block is removed. Another is to check for all BlockBreakEvents if there is a sign attached or standing on the block, and then cancel the event, which would solve half of the problem (think of a stack of sand, with a sign on the top block, breaking the bottom sand block of the stack).

If you have any additional suggestions about how to solve this problem then please let met know. I will at least try to implement one of the above solutions to solve part of the problem.

**Comment by confuser** [comment]
> Another is to check for all BlockBreakEvents if there is a sign attached or standing on the block

That's how I've solved this issue in the past. The BlockPhysicsEvent can then remain as it currently is.

**Comment by NLthijs48** [comment]
I think that would work, I'll make sure I change this for the next update (might take a few weeks, finishing my Bachelor degree currently).

Thanks for your report and input, if you have any other questions/problem then let me know.

**Comment by confuser** [comment]
Hi @NLthijs48 any updates on this?

**Comment by NLthijs48** [comment]
Was just planning to do some work on AreaShop, so when you reminded me here I first did this one, fix is described in the commit that is linked above.

**Comment by confuser** [comment]
Brilliant, thanks.

Have you got a CI (Jenkins) setup to download from?

**Comment by NLthijs48** [comment]
I do not have a build server like Jenkins, could give you a download though, which way can I give you a download link in private? Tried joining the frostcast teamspeak, but that does not seem to be online.

**Comment by confuser** [comment]
No worries, I'll get it setup on the Frostcast jenkins server later tonight, if you don't mind?

**Comment by NLthijs48** [comment]
That is fine with me, that will just pull the changes from GitHub and then build it right? Might be handy for me to link to when giving out builds, normally using Google Drive for that. Let me know if the builds succeed, because the Maven setup is kinda complicated. It also contains a task that copies the final build to my test server, that might be a problem for Jenkins.

**Comment by confuser** [comment]
@NLthijs48 http://ci.frostcast.net/job/AreaShop/

I haven't had time to confirm the integrity of the artifact, but the size seems to be in line with your uploads on Bukkit Dev.

It won't automatically build on pushes as it'll require a post commit hook in this repository's settings.

**Comment by NLthijs48** [comment]
The generated .jar file works perfectly on my test server, so it is correct :)

Should I add a Jenkins (git plugin) or Jenkins (GitHub plugin) hook in the repo? Did never set that up before.

**Comment by confuser** [comment]
If you set up the Jenkins (GitHub plugin) and set the following as the hook url, it should start automatic builds :)

`http://ci.frostcast.net/github-webhook/`

**Comment by NLthijs48** [comment]
Aha, based on the information on GitHub about the plugin I had set it to `http://ci.frostcast.net/job/github-webhook/`, changed it to the correct one and let it do a test-run, which worked.

**Comment by confuser** [comment]
For some reason my other projects are set to the URL in my previous comment, not sure why that didn't work. Glad it's all working now :+1:

**Comment by NLthijs48** [comment]
The url in my message is incorrect, that is what GitHub suggested, your url is the correct one and I'm using that now, my message was a bit unclear.

**Comment by NLthijs48** [comment]
Hey confuser, the Jenkins server now asks for a login when trying to access it, is that intended or not? 

I first tried joining the FrostCast TeamSpeak server to contact you, but it seems to be offline.

**Comment by EvilOlaf** [comment]
AFAIK are they migrating to another machine. Seems that this takes a while.

**Comment by NLthijs48** [comment]
Aha that would explain it, although it is not really a big problem for me that it is unavailable, I liked having the CI.

**Comment by confuser** [comment]
Apologies for the unexpected downtime, having problems with our provider. Currently seeking alternatives. I'll ping you @NLthijs48 when it's back up.

**Comment by NLthijs48** [comment]
Thanks for the message, nice that will let me know when it works again.

**Comment by confuser** [comment]
@NLthijs48 back up

https://ci.frostcast.net/job/AreaShop/

**Comment by NLthijs48** [comment]
Cool, thanks!
