### ISSUE TITLE
Signs only (no commands)

### ISSUE THREAD

**Issue by Nentify** [NLthijs48/AreaShop#150]
Is there a way to disable the commands when buying/renting/etc regions?

**Comment by jewome62** [comment]
You can use permission plugin as pex for forbide this command

**Comment by NLthijs48** [comment]
Removing the permission as @jewome62 suggest would not work, then players can also not use the signs anymore (the signs simply execute a command and therefore also need the permission).

What is the actual thing you try to prevent? Buying a region while in another world? Or buying a region while you are far away? or something else? The `default.yml` file already offers options to restrict buying/renting to the same world or inside the region, so that could be the solution.

**Comment by JonathanVil** [comment]
I guess he wants that the regions is only rentable by signs, and not by commands.

**Comment by NLthijs48** [comment]
@JonathanVil I understand that, but normally there is no reason at all for not offering the commands next to using the signs, so that is why I think one of my suggestions applies. Making a difference between clicking a sign and using a command won't happen, so looking for another solution is better in that case.

**Comment by Nentify** [comment]
The intention was you have to visit the 'estate agent' to purchase a region. 
On 5 Jun 2016 1:15 p.m., Thijs Wiefferink <notifications@github.com> wrote:@JonathanVil I understand that, but normally there is no reason at all for not offering the commands next to using the signs, so that is why I think one of my suggestions applies. Making a difference between clicking a sign and using a command won't happen, so looking for another solution is better in that case.

**Comment by NLthijs48** [comment]
Currently I won't add this so I'm closing the ticket. Technically hard/ugly to add and it has not much use in practice.
