### ISSUE TITLE
AreaShop is excessive loading chunks

### ISSUE THREAD

**Issue by kikelkik** [NLthijs48/AreaShop#157]
I've been testing plugin constellation, configuration, etc. for weeks on my Spigot 1.9.2 server and the result is that if I have AreaShop enabled, loaded chunks raise up to 1500 even when no player is on the server. For comparison: If AreaShop isn't loaded, loaded chunks are at 0 when nobody's online.
I can't explain why and don't know what to do else, so I wrote that ticket. 
config.yml: http://pastebin.com/RgarDpZb
default.yml: http://pastebin.com/WtS7Q3eA
I do have a lot of AreaShop regions (660) if it's important to know.

Looking forward for help!

~kikelkik

**Comment by NLthijs48** [comment]
At startup AreaShop updates all signs connected to regions to ensure they properly reflect your (possibly updated) configuration files. So this will load all chunks that a sign is in. Those chunks should be unloaded after a while though if I'm correct, I'm not totally into chunk loading and unloading though so I cannot exactly tell you how it works.

You can disable this sign update in [the config](https://github.com/NLthijs48/AreaShop/blob/master/AreaShop/src/main/resources/config.yml#L324-L326), the setting for doing that is missing from your config file because it has been added at a later point (you can just add it). Remember that disabling this means that you explicitly need to use `/as reload` to update all signs/regions after changing config values (or wait until the regions get updated by events like renting/unrenting).

Let me know if that is the information you need.

**Comment by kikelkik** [comment]
Alright thanks for your quick and very helpful support! That's the feature I was looking for and I whould very unlikely change my config that often so /as reload should be a compromise :D 
An advise for the future: You could try to automatically update the config if there are some changes when updating the plugin - so nobody whould be searching an option not exisiting in his old config. 

All in all hang on developing that awesome plugin! :)

**Comment by NLthijs48** [comment]
Nice that this is solved for you this way.

I have looked into automatically updating the config file a couple of times in the past, but it is quite a challenge. Simply loading the config file with the YAML parser and saving it again would remove all comments, so then all notes would be gone, which is very bad (for this reason AreaShop has read-only files like config.yml and default.yml, and read/write files for other files that you normally do not need to look into). There are some libraries out there that have limited support for comments, but most of them do not fit all requirements.

So I did not find something yet to tackle that problem sadly, manually rewriting it by reading the file as text seems like the 'best' option currently, but is not properly maintainable. For now I simply keep it like this, until I find something better.

**Comment by kikelkik** [comment]
For the time, you could mention to manually update the config e.g. in changelog or as a notification of AreaShop when joining the server.

**Comment by NLthijs48** [comment]
The changelogs do indicate that feature X has been added with config key Y, so in that sense they do already, you are right it could be a lot more prominent though. Notifying could get annoying quite quickly, so if I do that then it should be easy to turn off, for example by executing a command or clicking a thing in the notification text. Thanks for you input though :)
