### ISSUE TITLE
[Suggestion] Where the money goes? 

### ISSUE THREAD

**Issue by Blackyvk** [NLthijs48/AreaShop#16]
I'm building a server where money never dissapears or comes from nowhere.

Do you think its possible to add an account option where this money goes? like towny if you buy a region the money goes directly to the server account.

**Comment by NLthijs48** [comment]
I have already added this feature for the upcoming update. For each region you can set a 'landlord', which is a person that receives all the money made by the region. You can also set this for a group of regions, or all of them, which makes it possible to get the money to a server account.

You could temporarily solve your problem by adding commands to the eventcommandprofiles section in the config.yml to transfer money to the server account (variables for the price etc are available).

**Comment by Blackyvk** [comment]
oh... I didnt read the commits, so I tried to compile it and worked, but it adds an uuid, what could happen if this uuid logs in the server (i doubt it) with a different name. will it change the landlord name in my regions ?

Because the server economy doesnt have an uuid is just a name. It works like this but i wonder what could happen.

**Comment by NLthijs48** [comment]
It is almost impossible that a random player logs in with that exact UUID, not something to worry about I would say.

The problem that is causing the exception has been [fixed](https://github.com/NLthijs48/AreaShop/commit/93d56125137799725c8ccaf0fccdd7e8c9dba779). It is caused by the Bukkit API not returning a name for a player that has never visited the server (the server account in this case). So now I check if a name has been restored from the UUID before passing a transaction to Vault. If I cannot the name from the UUID, then it will fall back to the cached name (saved in 'general.landlordName' when setting the landlord). So this way the money should get transferred correctly. 

If you want to set the landlord in a group or default.yml, then make sure you set it for 1 region first, and then copy the landlord and landlordname settings from there, then it should work correctly.

Since you already compiled the sources yourself I assume you can easily pull my latest commit and build it again, if you however need a .jar file then just let me know and ill upload one somewhere.

**Comment by Blackyvk** [comment]
yes, I can do it, thanks for the fix it worked perfectly.
