### ISSUE TITLE
Non-cuboid regions?

### ISSUE THREAD

**Issue by thebeast5268** [NLthijs48/AreaShop#165]
I just want to know how to define non-cuboid regions for rent. Say a cube has a pyramid on top of it (Like a house with a steepled roof) how can I let players edit everything inside the blocks, but not the blocks themselves?

**Comment by NLthijs48** [comment]
You could use polygon regions, but capturing a pyramid with that does not work sadly. You would need to create a couple of regions covering the parts that you need, and then link hem together like described here: #131. AreaShop supports all WordGuard regions, so as long as you got a region in there with the correct blocks in it then it will work with AreaShop.

WorldEdit also supports `convex` type selections, which would be perfect for this situation, however WorldGuard does not support convex region though so that won't work. Example:

![2016-06-04_16 19 42](https://cloud.githubusercontent.com/assets/6951068/15800085/95c23158-2a70-11e6-820e-f43140159c4b.png)
