### ISSUE TITLE
/as info region x crashes the server

### ISSUE THREAD

**Issue by oloflarsson** [NLthijs48/AreaShop#183]
#### Current behavior
I have had to deny the permission node `areashop.info` for all players on the server because usage of that command softcrashes/hangs the server.

#### Steps to reproduce (for bugs)
1. Type /as info region someregion
2. The server will hang
3. https://gyazo.com/119549eef648f742b10ad6bfaae49b55

#### Your environment
* Server platform: PaperSpigot 
* Server version: This server is running Paper version git-Paper-809 (MC: 1.10.2)
* AreaShop version: Jenkins Build 44
* WorldEdit version: Bukkit-Official (6.1.4-SNAPSHOT;3583-28d4587)
* WorldGuard version: WorldGuard 6.1.3-SNAPSHOT;1679-f006a95
* Vault version: http://dev.bukkit.org/bukkit-plugins/vault/files/52-vault-1-5-6/

**Comment by NLthijs48** [comment]
I knew it would cause an exception and possibly kick the client if you have a lot of regions, but I did yet see the server crashing because of this. Issue #172 will solve this problem though, I'll give that more priority.

Are you using a custom language file made with an older version of AreaShop? Because it looks like the replacements applied in your message are incorrect. The language file changed a lot in the dev build, so you would have to recreate custom language files.

I'll close this issue, #172 will keep tracking this problem.

**Comment by NLthijs48** [comment]
@oloflarsson Pages have been implemented, see 8143bdae277709dd5a15abc03e32f867926afba0, build available at http://wiefferink.me:8080/job/AreaShop/ as usual. If you find other places pages should be added let me know.
