### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by JoHnnYY01** [NLthijs48/AreaShop#214]
Hi,
1:
First I need to say that  I checked permissions and I didn't found what I was searching for. Basically only ops can make rent,buy... signs. When non-op try to make it it says that he doesn't have permission to set signs. Is there a permission for that?
2:
When somebody buys region he becomes member of region. Why? Can I make that person who buys region to be owner and landlord of that region immediately after buying it and if somebody rents in to be member?

**Comment by NLthijs48** [comment]
1. [These](https://github.com/NLthijs48/AreaShop/wiki/Commands-and-Permissions#as-add-rent-buy-region-world) are the permissions you are looking for (they are listed at the `/as add` command).
2. Because member normally allows you to do enough in the region. You can also [add them as owner instead](https://github.com/NLthijs48/AreaShop/wiki/Frequently-Asked-Questions#how-can-i-set-the-buyerrenter-as-owner-of-a-region-instead-of-member). Do you first want the region to be a buy region, and when somebody buys it it should become a rent region and get a landlord? You can use the `eventCommandProfiles` section in the `config.yml` file to do this.

**Comment by JoHnnYY01** [comment]
For the second question:
No, I dont want when somebody buys it to become rent region I am just giving you example because player can't use any of those functions. Thing that I want is when player buys region he becomes owner of it, but if region(not the same one) is for rent and somebody rents it the person who rented it becomes member of region he rented. It's like on the Hellominers server(idk if they use your plugin but it's very similar) When I rent region I become member and when I buy It I become owner and as owner I can add or remove members and owners and do everything in region.
I tried to add some commands to eventcommandprofiles but it didn't work probably I didn't wrote command good.

**Comment by NLthijs48** [comment]
I still dont see why you sometimes want them as members and sometimes owners. If a player has rented/bought a region with AreaShop then they can simply use `/as addfriend` to add people to the region. So in my opinion giving them the WorldGuard commands to add/remove members is a bad idea.

**Comment by JoHnnYY01** [comment]
Oh yes I forgot about add friend... You probably don't understand because my english is bad sorry. I am saying that player who rents region he becomes member of it and the player who buys region he becomes owner of it. I will try with eventCommandProfiles just tell me how should i write commands in it? Should I use / or not and can I use only areashop commands or I can use commands from all plugins. Anyway I tried to everything with world guard commands because I used them on other servers more. I will try all of this tommorow (I am watching Basketball now :) ) and I will tell you if it worked.
PS: Great plugin!

**Comment by NLthijs48** [comment]
"I still don't see why you sometimes want them as members and sometimes owners.", why do you need them to be members sometimes and owners sometimes? It looks like you are not solving your actual root problem.

If you still want to do it, forget the 'eventCommandProfiles', simply use the 'flagProfiles' section. For the sold, forsale and resale states change the line starting with 'members:' to start with 'owners:', and keep the 'members:' lines for the other (rent related) states. Then people that rent will be member, people that buy will be owner. Do you want people to buy and rent the same region? Because that is impossible.

**Comment by JoHnnYY01** [comment]
You just explained thanks I will do that. I don't want to rent and buy same region that does not make any sense.

**Comment by JoHnnYY01** [comment]
Sorry for misunderstanding.
