### ISSUE TITLE
Regions randomly selling themselves w/o the players running any command

### ISSUE THREAD

**Issue by Purevega** [NLthijs48/AreaShop#226]
#### Current behavior

Players have informed me that their properties sell themselves randomly.

#### Steps to reproduce (for bugs)

1. 
2. 
3. 
4. 

#### Your environment

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version:  1.10
* AreaShop version: Latest
* WorldEdit version:  6.1.3
* WorldGuard version:  6.1.2
* Vault version: 1.5.6

**Comment by NLthijs48** [comment]
The only reasons why this could happen are the following:

- Executing the `/as unrent [region]` command. This also happens when a player shift-right clicks a sign that is linked to the region.
- The region is removed from AreaShop by `/as del [region]`, assuming the region is still listed in `/as info all` this is probably not what happend.
- The region expired
- You have the `inactiveTimeUntilUnrent` in the `default.yml` file set and the player has been offline for that time period.

You also might want to check the log file to see if AreaShop logs anything abnormal.
