### ISSUE TITLE
Extend rent question

### ISSUE THREAD

**Issue by Elioz** [NLthijs48/AreaShop#227]
Hello!, I have player shops for rent in my server for 2 weeks duration.
Right now they can extend the renting time with unlimited times and it's fine
the problem is that I want them to be able to extend the rent when they have 7 days left or less.
is it possible?

Thanks!

**Comment by NLthijs48** [comment]
Set the `maxRentTime` in the `default.yml` file to `21 days` and it should do exactly what you want. This means that the maximum time a player can have its region rented is 21 days, which means that they can extend it when it has 7 days or less left (because then adding 14 days will not go over 21 days).

Let me know if that solves your problem.

**Comment by Elioz** [comment]
Seems like it's working! thanks for your help!
