### ISSUE TITLE
My players can not put signs down it says tha blcok is not allowed here or something

### ISSUE THREAD

**Issue by ThunderBuddy34** [NLthijs48/AreaShop#233]
#### Steps to reproduce (for bugs)

1. 
2. 
3. 
4. 

#### Your environment

* Server platform (Bukkit, Spigot, etc.): 
* Server version:  craftbukkit version-spigot-9797151-301db84 (mc:1.10.2) api version 1.10.2-r0.q
* AreaShop version:  2.3.2
* WorldEdit version: 6.1.3
* WorldGuard version:  6.1.2
* Vault version: idk

**Comment by NLthijs48** [comment]
This is probably a WorldGuard problem, but you do not describe your situation at all, so I can only guess. Please describe a specific situation that does not work (test it yourself instead of relying on some rumour of your players) and show me the output of the `/region info <regionname>` command for the AreaShop region and all other regions that are at the same spot.

**Comment by NLthijs48** [comment]
I'm assuming you have solved the issue
