### ISSUE TITLE
Version for 1.7.10

### ISSUE THREAD

**Issue by Vankka2** [NLthijs48/AreaShop#236]
#### Current behavior

when i do /as it comes up with /areashop or /as

#### New behavior

it should come up with the help menu

#### Steps to reproduce (for bugs)

1. Install any version from https://mods.curse.com/bukkit-plugins/minecraft/regionbuyandrent#t1:other-downloads (CB 1.7.9-R0.x)
2. Do: /as
3. 
4. 

#### Your environment

* Server platform (Bukkit, Spigot, etc.): Thermos
* Server version: 1.7.10
* AreaShop version: https://mods.curse.com/bukkit-plugins/minecraft/regionbuyandrent#t1:other-downloads (CB 1.7.9-R0.x)
* WorldEdit version: 6.1.3
* WorldGuard version: 6.1.2
* Vault version: Latest (no update notifications coming up)

**Comment by NLthijs48** [comment]
You link to the AreaShop version links to the download page and not a specific version. I assume you installed V2.1.0 since that is listed as Minecraft 1.7.9? Minecraft 1.7.10 is still supported by the latest AreaShop version, so I advice you to install the latest one and see if that works. If it does not work, please give me the contents of the `latest.log` file that can be found in the `/logs` folder of your server.

**Comment by NLthijs48** [comment]
I'm assuming you have solved the issue
