### ISSUE TITLE
Blacklist per plots

### ISSUE THREAD

**Issue by Sprungente** [NLthijs48/AreaShop#239]
Could you add a feature, that give user an option to take people on a blacklist? When player "def\* is in the blacklist from plot 001 that owned by Player "abc" then can "def" not enter this plot. 

This will be reset, when the plot change the owner.

Hope you can understand my bad english :/

**Comment by NLthijs48** [comment]
It might be possible to add this, it would not be great performance-wise though and could cause lag if used intensively. To get a better idea about the feature, I have some questions for you. Why do players want to prevent others from entering the plot? Are they walking in front of where they want to build? Are they messing with redstone? Or something else? Depending on your answer of that question something else than a blacklist might be a better solution.

**Comment by Sprungente** [comment]
Any players has sometimes dispute. Then they provocate the other with a visit to his plot. The other will be angry... like nursery. And everytime involve and stop the dispute is... shit. I think you know what i mean.

An option is with worldguardflag. But i think an easier option for the players. Maybe with /as addblacklist and /as delblacklist.

You can like the greeting WG-flag on Plotcreate solve this command. 

and im sorry for the late answer and thanks^^

**Comment by NLthijs48** [comment]
The worldguard flag is hard to use for this purpose, because it can only block groups of people. I could deny all members of the region entry, and allow owners, but that means the renter/buyer of the region always has to be added as owner instead of member of the region. Keeping the players out with AreaShop itself could be done, but is messy, so I would like to use the WorldGuard feature or don't add it at all probably.

There are also plugins that allow players to keep other X blocks away, maybe that is more appropriate because that prevents other players from standing in the way while they try to build.
