### ISSUE TITLE
Exeeded the block limit, when theres plenty of blocks left.

### ISSUE THREAD

**Issue by FrozenBeard** [NLthijs48/AreaShop#242]
/rg select s25 (select my region)
//size
Tells me the region size is 7395 blocks, the default limit to restoring a schematic maximumBlocks: 1000000 this is far under the maximum limit, but when I unrent that areashop I get this in the console:

> [AreaShop] Exeeded the block limit while restoring schematic of s25

why would this be?

**Comment by NLthijs48** [comment]
I'm not sure what causes this problem, AreaShop should pass the limit set in the config to WorldEdit and normally saving/restoring schematics does not have problems with anything below that limit. Do you maybe have AsyncWorldEdit or FastAsyncWorldEdit installed? Because at least AsyncWorldEdit has config options to change the maxChangedBlocks limit, which might be overriding the value set by AreaShop.

To make debugging easier I have added the limit set by AreaShop and the limit indicated by WorldEdit in the exception in the logging message. If you install a [development build of AreaShop](http://wiefferink.me:8080/job/AreaShop/) then you will have these updated messages and can see if AreaShop sets the low limit or if another plugin does that.

Let me know if you managed to solve your problem.

**Comment by NLthijs48** [comment]
I assume the problem is fixed.

**Comment by FrozenBeard** [comment]
Ah no sorry, I never replied to your responce!
I do have AsyncWorldEdit installed. Here is my config http://pastebin.com/k6Cy7wPv
I will give the Dev a go.
