### ISSUE TITLE
Players cannot use Shift right Click to Sell Area's

### ISSUE THREAD

**Issue by lewishackfath** [NLthijs48/AreaShop#243]
#### Current behaviour
When a Player Shift Right Clicks a Sign the get the following message:

"You do not have permission to send Area Shop Messages"

players can still sell using /as sell while standing in their region.

#### New behavior
Players should be able to sell their area

#### Steps to reproduce (for bugs)
Shift Right Click Sign of a Purchased Area

#### Your environment

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.10.2
* AreaShop version: v2.3.2#CUSTOM
* WorldEdit version: v6.1.3;7a097ca
* WorldGuard version: 6.1.2:e38d98d
* Vault version: 1.5.6

List of Installed Plugins:

-Worldedit
-idisguise
-groupmanager
-effectlib
-instantdecay
-commons
-simplelocalchat
-vault
-globalgroupmanager
-worldguard
-dynmap
-heroes
-areashop
-essentials
-killermoney
-essentialsspawn
-magic
-quests

**Comment by NLthijs48** [comment]
Updating your `signProfiles` section of the `config.yml` file to the [updated one here](https://github.com/NLthijs48/AreaShop/blob/master/AreaShop/src/main/resources/config.yml#L93-L153) fixes the problem. The `/areashop message` commands are accidentally executed by the player itself in the config of the release version, which is incorrect. Instead of replacing the complete config part you can also change all section names where `/areashop message` commands appear to end in `Console` instead of `Player`.

Let me know if that worked for you.

**Comment by lewishackfath** [comment]
This Worked Perfectly Thanks.
