### ISSUE TITLE
Blacklist command (and issue)

### ISSUE THREAD

**Issue by HanatakeYurii** [NLthijs48/AreaShop#248]
Hi,
First I would like to thank you for your plugin, that is doing great on our servers.

Second I will point you a small issue we encountered some times before:
We have cities and plots in them for new player to build a house. All of them are WG regions.
When we try to add a plot to areashop with "/as add buy" while standing in the plot, it says that there are multiple regions on that position, but keep adding them to AS. That make the cities buyable and deletes all owners and members which is not what we want.

I know that blacklist could avoid this, but should not it be not adding any region to AS when there is doubt on which region to add?

Last, I would ask you if it was possible to add a command for adding a region to the blacklist and another one to see which regions are on it?

Anyway thanks

**Comment by NLthijs48** [comment]
Good to hear AreaShop is used on your server with success :)

Using the `/as add buy` command without specifying a region will add all regions it can find inside your WorldEdit selection, so not only the region you are standing in. That is why also bigger regions are added to AreaShop while they should not be.  There is already [a feature request](https://github.com/NLthijs48/AreaShop/issues/191) for adding a confirmation to commands using WorldEdit selections, to make it more obvious what is about to happen. In addition to this I might also be able to detect the big city regions and exclude them from the selection automatically.

Adding a command to add regions to the blacklist is not possible currently, because that would mean changing the `config.yml` file and when I would save that file all comments and formatting is lost. There are some solutions to this problem, but most of them far from ideal. So until that problem is solved a command like that will not work without major side effects, I do support the idea of adding a command like this though.

**Comment by HanatakeYurii** [comment]
Thanks for the response, and sorry for the late mine. It's good to hear you have plans.
Excluding too big regions from automatic selection could be a good way, at least with a confirmation.

As developper, I understand for the blacklist. Imho, the only suitable way should be creating a specific and separate file for the blacklist. But that's not a major issue, I keep adding them manually for now. I'm glad you're liking the idea thought.

Have a Happy New Year

**Comment by NLthijs48** [comment]
Closing the issue because it is not possible as agreed upon, but I will keep in mind improvements for this for the future.

**Comment by HanatakeYurii** [comment]
Thanks
