### ISSUE TITLE
[request] Adding cooldowns and warmups to /as tp <name>

### ISSUE THREAD

**Issue by FrozenBeard** [NLthijs48/AreaShop#250]
We have cooldowns and warmups on our server for teleporting to stop people fleeing PVP, could you please add an option for warmups and cooldowns for the use of the teleport command.

**Comment by NLthijs48** [comment]
I get that the instant teleportation is a problem in some server types, but decided against implementing as described in #60 because it is better that another plugin covers all warmups/cooldowns instead of each plugin with a teleport command implementing his own system.

Let me know if you feel that AreaShop still needs this or not.

**Comment by FrozenBeard** [comment]
The MyCommand cooldown was my fallback if you didn't implement, I already have this working on another command, it would be better to have it built in, instead of duct taping a solution, but if you don't want to add it thats fine, ill have to do the same method as the other guy that requested it.
