### ISSUE TITLE
Update AreaShop for WorldGuard 6.2.0

### ISSUE THREAD

**Issue by jewome62** [NLthijs48/AreaShop#252]
Hi,

I'm not already tested this. But a new update of WorldGuard is release.
https://dev.bukkit.org/bukkit-plugins/worldguard/files/48-world-guard-6-2-for-mc-up-to-1-11/

There are a warening into release note, which can be read with attention

> CUSTOM FLAGS USERS:
If you used a third-party plugin that added custom flags to WorldGuard, it may stop working with 6.2. It is highly recommended you backup your region files. Although WorldGuard will attempt to preserve the flags, they will likely be non-functional. Now that WorldGuard natively supports a custom flags API, third-party plugins will have to update to the new API before they work again.

I know AreaShop add flag into worldguard region.
We must verify this.

I try to test it this week.

Thanks

**Comment by NLthijs48** [comment]
Thanks for the heads up.

I have updated AreaShop just now which works with the new WorldGuard version, the previous AreaShop release had a stupid mistake that I had already fixed in the development builds, so I only had to upload the new version.

The warning from WorldGuard about custom flags is not meant for AreaShop, because AreaShop only sets flags that already exist and all other data is saved in the AreaShop files itself.
