### ISSUE TITLE
AreaShop TP Bug

### ISSUE THREAD

**Issue by AgentCortez** [NLthijs48/AreaShop#261]
#### Current behavior
When players do /as tp PLOTNAME it says:
"No safe position found in plot-101, no spots in the region left or maximum tries exceeded (50000/50000)"

However whenever a player has cleared the bottom of their plots (at bedrock) and use the tp command, they get teleported to the bottom of their plot.

#### New behavior
This should teleport you right outside the plot so that you're facing.

#### Steps to reproduce (for bugs)
1. Set up a plot that goes up to Y: 150 from 0
2. Rent the plot
3. type /as tp plot

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): Paper Spigot
* Server version: git-Paper-895 (MC: 1.10.2) (Implementing APU version 1.10.2-R0.1-SNAPSHOT)
* AreaShop version: 2.4.0
* WorldEdit version:  6.1.3;7a097ca
* WorldGuard version: 6.1.2;e38d98d
* Vault version: 1.5.6-b49

#### Your config files (for bugs)

[AreashopFiles.zip](https://github.com/NLthijs48/AreaShop/files/643367/AreashopFiles.zip)

**Comment by NLthijs48** [comment]
This is not a bug, let me explain: By default AreaShop tries to teleport you right in the middle of the plot (on the x, y and z axis), but if that is not a safe location (floating in the air, lava, etc) then it will try to find a spot close by. So it searching around this middle point until a safe location is found, or the search limit is hit (as is the case with your plots).

Now about solving the issue, in `default.yml` you can set the `teleportLocationY` setting, this determines the location on the Y axis where AreaShop should start looking for a safe teleport location. You can adjust this setting to the ground level of your plots to let the search succeed. Teleporting players outside a plot is only done when `teleportIntoRegion` is `false`, but since it starts searching from the middle it normally does not teleport outside the region (depends on region size).

You can also set the teleport location with `/as settp`, the renter/buyer of the region can also use that. As last you can also teleport to the sign of the region, maybe that helps you out with teleporting outside the region like you want.

Let me know if you problem is fixed.

**Comment by NLthijs48** [comment]
I assume your problem is solved/answered
