### ISSUE TITLE
Display as regions in "resale" mode when using "/as info forsale"

### ISSUE THREAD

**Issue by IDLauncher** [NLthijs48/AreaShop#263]
**Current behavior**
Regions in resale mode are omitted from the returned listings.

**New behavior**
Regions in resale mode are displayed alongside the standard forsale list.

**Comment by NLthijs48** [comment]
Resale regions are indeed not listed in `as info forsale`, they are listed in `as info reselling` though. Technically the region is still sold to the current owner, so that is why a region does not get listed in the forsale category, but are listed in the sold category.

I might add them to the forsale category as well, but I'm not sure about it yet. To get a better idea why you miss them I have some questions: do you want to list the region for administration purposes? Or do your players want to check the regions that are available? Might allowing a command like `/as info forsale,reselling` (which would list both of the categories) be a solution?

**Comment by IDLauncher** [comment]
Derp. I didn't know that. In that case, I just want that info added to this page:
https://github.com/NLthijs48/AreaShop/wiki/Commands-and-Permissions

I noticed this on a server that did not yet have a version that had the "reselling" partameter, and at the time, it just meant that anything in resale I could not find out about. Then I went and tested it on a server of my own, and noted that the resale properties don't show up, not realizing there was a parameter in the new version that I didn't have in the old version.

My bad.

**Comment by NLthijs48** [comment]
It is indeed missing on the page, fixed that now. I recommend checking the commands ingame by the way, if you simply don't provide the arguments it needs then it will show you the options. The one of `/as info` can even be clicked 😄 

![screenshot_1](https://cloud.githubusercontent.com/assets/6951068/21439165/c3b60afc-c88c-11e6-8208-ba32ff7c1600.png)
