### ISSUE TITLE
Folder not appearing 

### ISSUE THREAD

**Issue by Awsomebulderguy** [NLthijs48/AreaShop#265]
#### Current behavior

Even thought the plugin is installed, it does not show that it is installed.
There is also no config.yml in the folder that it should be in. I am using server.pro to host my server.
#### Steps to reproduce (for bugs)

1. 
2. 
3. 
4. 

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): 
* Server version: 
* AreaShop version: 
* WorldEdit version: 
* WorldGuard version: 
* Vault version:

**Comment by NLthijs48** [comment]
Did you check the log file or console output? It might be that AreaShop did not startup correctly, for example because WorldEdit, WorldGuard or Vault is not installed. Normally you can find the log file at `/logs/latest.log`, if you show that file to me I can tell you what is wrong (if it is not clear already from the text in the log).

**Comment by Awsomebulderguy** [comment]
I realized that vault is not installed correctly. I'm going to try it again
