### ISSUE TITLE
Greetings and other per-region events

### ISSUE THREAD

**Issue by doodzio** [NLthijs48/AreaShop#271]
#### Current behavior 
World Guard supports only one greeting etc.
So there is no option to have other greeting  style (etc. ) for other players groups (e.g. u set greeting flag to g:member Hello then nobody else see this ).

#### New behavior
Can we add option parent for region and for regions group?
Nothing change in plot region /group

**Comment by NLthijs48** [comment]
I understand that WorldGuard only has one greeting per region, but I don't understand what you would like me to add. Could you try to explain in more detail what you would like to see added to AreaShop? If it helps, show what the config would look like.

**Comment by doodzio** [comment]
Thank you for reply.
Sorry for my English. 

Now I just ended reading documentation. (many times)
Its look that I can done it in
groups.yml => <groupName> => general => flagProfile =>parent
and
BTW what about add variable %group%  #Isnt specified in variables
Example of use:
group.yml =><groupName> => general => eventCommandProfile => created => before => ["region define -g %group%_parent" ] 

Sorry for mess I did.
And THX you for that great Plug-in.

**Comment by NLthijs48** [comment]
If you are in `groups.yml` already, then you are setting the flagProfile for a specific group, therefore you can just use the name of that group instead of a variable for it. Adding a `%group%` variable is not possible, since a region can be in more than one group, and these variables work everyone the region is used. If you want to set something for all regions, you need to use `default.yml`. Setting region flags by command is not necessary, as you have shown yourself you can use `parent` to set the parent of a region.

Can I close this issue or is there still something that you would like to have added?

**Comment by doodzio** [comment]
Yes. Thx for all. 
And once again.
Sorry for mess I done.
