### ISSUE TITLE
Security Leak!!! Player could spam items by continusly buy/sell rent/unrent regions!

### ISSUE THREAD

**Issue by k-jiang** [NLthijs48/AreaShop#273]
#### Current behavior

Player could spam items by continusly buy/sell rent/unrent regions when restore is enabled

#### New behavior

Please add option to disable the schematic saving when unrent / sell a region

#### Steps to reproduce (for bugs)

1. Enable restore of a region: ``/as setrestore a-region-id true``
2. Throw something into the region, e.g. diamonds
3. Buy / rent it: ``/as buy a-region-id`` ``/as rent a-region-id``
4. sell(unbuy) / unrent it: ``/as sell a-region-id`` ``/as unrent a-region-id``
5. Repeat setp 3 and 4, then you will find your diamonds get doubled every time!!

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.11.2 build 1129
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.5
* WorldGuard version: 6.2.1 build1696
* Vault version: 1.5.6

#### Your config files (for bugs)

(You don't need to have a specific configs to duplicate this problem)

### I like your plugins and you work very much. Please consider fix it immediately since this is causing huge security leaks to all servers.

**Comment by k-jiang** [comment]
I just figure it out. The problem is when you first install you AreaShop, you default.yml is probably looks like this:
```  enableRestore: false
  schematicProfile:
    created:
      save: '%type%-%region%'
      restore: ''
    deleted:
      save: ''
      restore: '%type%-%region%'
    rented:
      save: '%type%-%region%'
      restore: ''
    unrented:
      save: ''
      restore: '%type%-%region%'
    bought:
      save: '%type%-%region%'
      restore: ''
    sold:
      save: ''
      restore: '%type%-%region%'
    resell:
      save: ''
      restore: ''```

So if you don't want your player spam items in you selling / renting regions, just delete what follows the "save" option. Especially in "rented" and "bought". It should look like:
```  enableRestore: false
  schematicProfile:
    created:
      save: '%type%-%region%'
      restore: ''
    deleted:
      save: ''
      restore: '%type%-%region%'
    rented:
      save: ''
      restore: ''
    unrented:
      save: ''
      restore: '%type%-%region%'
    bought:
      save: ''
      restore: ''
    sold:
      save: ''
      restore: '%type%-%region%'
    resell:
      save: ''
      restore: ''```

The downside of this would be you are no longer be able to do "setrestore" after your region is created in AreaShop, unless you manually modify your region.yml and paste your schematic file into the schem folder.

Also I highly suggest @NLthijs48 to set the default value of these two to never save the schematic when bought/rented so people don't get confused.

Peace!

**Comment by NLthijs48** [comment]
I recently changed the default to save the schematic at rent and buy, because a lot of people had trouble enabling the restore option after adding regions. This problem with items is serious though and I would like to fix it. The best option to me seems like excluding entities from the saved schematic, that would solve this problem. There are some things to consider though, for example you might want to keep saving item frames. That would still not properly solve the issue though, since then it would place item frames again and again at the same spot.

I need to think about a good solution for this, maybe a setting to disable saving/restoring entities in schematics.

**Comment by k-jiang** [comment]
Why not just save the schematic automatically when issued `/as setrestore a-region-id true`?

**Comment by NLthijs48** [comment]
The filename of the schematic is defined in the `schematicProfile` setting of the `default.yml` file and depends on a region event. Enabling restore does not belong to any of those events, so we don't know which event to use. Simply using the `created` event would be wrong, because that could save player created stuff to the schematic if the region is already rented/sold at that point.

**Comment by k-jiang** [comment]
There is another way: Just show a message to OPs that they need to do a manual `/as schemevent region-id created` after `/as setrestore a-region-id true`.

**Comment by NLthijs48** [comment]
Fixed properly for WorldEdit 7, maybe for WorldEdit 6.

Could decide to add this to the config, so that save/restore of entities can be enabled again at the risk of the server owner.
