### ISSUE TITLE
problem with anything areashop sign related

### ISSUE THREAD

**Issue by RudyPooh** [NLthijs48/AreaShop#276]
#### Current behavior broken

anything with areashop signs i have a problem with if im trying to make a shop for someone to buy i set up the sign correctly it works and everything but if the person hits the sign to buy the plot or tp to the plot or basically anything with the sign it says an internal error has occurred wile attempting to perform this command so i tried to do it with renting a plot and it says the same thing i even tried it with /as add and still nothing i have all the required plugins and everything's right just cant actually buy/sell/rent or anything to another player the same error just comes up every time 
#### New behavior 

a player should be able to hit the sign then commands come up in there chat that they can click to do whatever to the plot but they cant it just says that an internal error has occurred wile attempting to perform this command

#### Steps to reproduce (for bugs)

1. i dont know how it can be triggered 
2. 
3. 
4. 

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): 
* Server version: 1.7.10
* AreaShop version: 2.3.2
[AreaZip.zip](https://github.com/NLthijs48/AreaShop/files/722737/AreaZip.zip)

* WorldEdit version: 5.6.3
* WorldGuard version: 5.8
* Vault version: 1.2.27

**Comment by NLthijs48** [comment]
Show me your `latest.log` file, the error is shown in there and will allow me to see the problem. AreaShop 2.4.0 is already released, so you could at least try upgrading to that version to see if that makes a difference. I also recommend that you update WorldEdit and WorldGuard to the latest version, the 5.X versions are really old. Same for Vault, there is a lot newer version for that.

I actually think the problem is Vault, because AreaShop only supports 1.4.1 or higher.

**Comment by NLthijs48** [comment]
I'm assuming your problem has been fixed
