### ISSUE TITLE
Pls add a GUI for the commands

### ISSUE THREAD

**Issue by Enoceant** [NLthijs48/AreaShop#279]
#### New behavior

Hi, can you pls add a Gui for all the commands, so when they do /as gui or something
There will be a pop up and all command will be listed there so for example:

The player can press:

Info- /as me, shows landlord and other members of the house
Teleport - opens another gui page that shows all houses that you can teleport to
Friends - add, remove, etc
House
   - Rent 
   - Un Rent
   - Sell
Etc...

And there is a back button on the bottom of page to go back to main- only shows when pressed on a 
Rent, unrent, tp, sell, etc buttons

#### Steps to reproduce (for bugs)

1. 
2. 
3. 
4. 

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): 
* Server version: 
* AreaShop version: 
* WorldEdit version: 
* WorldGuard version: 
* Vault version:

**Comment by Enoceant** [comment]
This will allow me to use command npc so when player rot click this npc, this gui will show up
Using this for rpg server, very great plugin

**Comment by NLthijs48** [comment]
The idea for this has been around for a while, see #25, but I'm not too interested into it since it has some limitations. When you open an inventory the only way to see what an item does is hovering over it. So to find the region you need you need to go over each item in the chest, which is really impractical. Of course in practice players will often have just a few regions, so the problem would be minimal. For things like buying kits I think chest gui's are good, because with the item you can show a hint of what the kit is, but for regions this is not really possible (except maybe a different block depending on rent or buy region).

So because of these reasons I implemented clickable chat messages, because those can properly show what they do without the need to hover them.

I'm closing this issue and keeping #25 to track the gui.
