### ISSUE TITLE
Item Frames Do Not Restore.

### ISSUE THREAD

**Issue by JoelDesante** [NLthijs48/AreaShop#290]
#### Current behavior
Basically when I use the restore function, If the previous player had placed an item frame on something, the item frame won't be deleted upon restoring. Instead, it's left up to the game to delete the ones hanging in the air. Sometimes they don't go away.

#### New behavior
Basically, make it so that item frames will be deleted too! 😄 

#### Steps to reproduce (for bugs)
1. Restore an area shop with item frames in it

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.11.2
* AreaShop version: Latest
* WorldEdit version: Latest
* WorldGuard version: Latest
* Vault version: Latest

#### Your config files (for bugs)

I can not get this at this time.

**Comment by NLthijs48** [comment]
Issue #28 has already been opened to prevent this from happening, it is not that easy to add though so that is why it has not been implemented yet and is already open for a long time. If item frames are not going away while they are hanging mid-air you are having a problem with Spigot itself, it does happens sometimes though.

So there is not much I can do for you soon, and I'm closing this issue and keep tracking the problem at #28.
