### ISSUE TITLE
french translation

### ISSUE THREAD

**Issue by Aviorleking** [NLthijs48/AreaShop#296]
#### Current behavior

the greeting-forrent option in french config file say Plot peut être loué pour 1000€ pour une durée de 1 day

#### New behavior

it should say say Plot peut être loué pour 1000€ pour une durée de 1 **jour(s)**

**Comment by NLthijs48** [comment]
The original of that message is the following:
`%region% can be rented for %price% per %duration%.`

And the translation is like this:
`%region% peut être louée pour %price% pour une durée de %duration%.`

The `1 day` in your message actually comes from the duration that is set on the region. To fix the problem you can add the French day/hour/month/etc specifiers in the `config.yml` file and change the duration of the rent to use the French words. Either change the duration in `default.yml` or use `/as setduration <number> <type> [region]`.

Let me know if that worked for you.
If you want to help translating/improving for the French language you can check out [this page](https://github.com/NLthijs48/AreaShop/wiki/Language-support#translating-on-transifex) :)

**Comment by Aviorleking** [comment]
no it's saying the same things
[config.zip](https://github.com/NLthijs48/AreaShop/files/836175/config.zip)


wouldn't be better if this is in the language file ?

**Comment by NLthijs48** [comment]
Did you change the duration of the region? Because AreaShop simply shows your input as the duration. The settings in the config are only to determine the correct time to use for expiring the region.

I thought about adding it to the language file before, but there are some practical problems with that. I'll see if I can do something to improve it.
