### ISSUE TITLE
Resell flagProfile of default.yml incorrect & incorrect tag in lang for greeting-resale

### ISSUE THREAD

**Issue by electro2560** [NLthijs48/AreaShop#303]
#### Current behavior
Currently the RegionState enum has a value of "resell". In the current default.yml config, "resell" is used correctly in configuration sections such as signProfile, schematicProfile, eventCommandProfile; however, the flagProfile section uses "resale" causing regions for resell not to update their members or greeting by default.

Broken behavior: http://i.imgur.com/2Bl9xQ4.png
When path is fixed: http://i.imgur.com/qw4OJk3.png

#### New behavior
Update default.yml to change 'general.flagProfile.resale' to 'general.flagProfile.resell'  or replace line 46 of GeneralRegion#updateRegionFlags(GeneralRegion) to use the 'resale' path rather than 'resell' like this: 

Before: `ConfigurationSection stateFlags = flagProfileSection.getConfigurationSection(region.getState().getValue());`
After:  `ConfigurationSection stateFlags = flagProfileSection.getConfigurationSection(region.getState() == GeneralRegion.RegionState.RESELL ? "resale" : region.getState().getValue());`

There is also an issue with the default tag used in the language files. In the main class the tagResellPrice and tagRawResellPrice are used for tag replacement in BuyRegion#provideReplacement(String) and have the values of "resellprice" & "rawresellprice". They are used correctly in the default.yml 'general.signProfile.resell.line3' by default. However, they are used incorrectly in the language files for 'greeting-resale'. The 'greeting-resale' should either be updated to use the proper tag %resellprice% rather than it's default %resaleprice% value or %resaleprice% should be added as a tag.

Current BuyRegion#provideReplacement(String): https://pastebin.com/2K57iGAR
Fixed by adding that tag: https://pastebin.com/dzSXpGFH

#### Steps to reproduce (for bugs)
1.  Purchase a buy region
2. Put it up for resale
3. Walk into the region and note the greeting message will not have updated to what it should have in the default.yml

#### Your environment (for bugs)
* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.11.2R1
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.3
* WorldGuard version: 6.1
* Vault version: 1.5.6

#### Your config files (for bugs)
Default plugin generated default.yml: https://pastebin.com/YeiKWfMD
Manually fixed path (specifically compare lines 120): https://pastebin.com/jycy4LAZ

Using default EN.yml language file. I've made no changes during testing: https://pastebin.com/uCzsEYPn

**Comment by NLthijs48** [comment]
Thanks for the detailed report! Looks like I made a mistake when moving those options from `config.yml` to `default.yml` and refactoring them a while back. Tomorrow I can look further into it and implement a fix for these issues.

**Comment by NLthijs48** [comment]
After checking when this problem was introduced for a while it looks like this has never worked in the first place. So this bug might have been there since the introduction of `/as resell`, which is years ago. Before the introduction of the `ALL` flagProfile section it was not really a problem, since the members of the `sold` state would still be there, now however those are cleared and the region cannot be used while reselling it. 

I changed the `resale:` in the `default.yml` file to `resell:` so that this problem is fixed. I also added a fallback to the code so that old/wrong configuration files will be read correctly (if the `resell` section is not found I get the `resale` one). I updated the language file to use the proper tag, so next update of AreaShop that is also fixed for everyone (each server startup the language files are copied from the jar to disk again, overwriting old ones).

Once again thanks for reporting these problems with solutions and everything :) If you ever need help with AreaShop let me know!
