### ISSUE TITLE
new feature with stack command

### ISSUE THREAD

**Issue by BabelSolea** [NLthijs48/AreaShop#309]
hello!

do possible way to add this feature in near future?

when lauch stack command that create regions and load schemevent what using bundle of schematics:

like i put in schem folder schematics with 10 variants of region with different buildings

and stack command create regions and paste random schematics with random rotate?

that give thing to create randomaly city streets =)

**Comment by NLthijs48** [comment]
By using the optional group argument you can assign the regions created by `/as stack` to a group immediately, which allows you to paste a schematic. In the group you assign to the regions you can use the `created` section of `schematicProfile` to paste the schematic your want in the regions. This does not support randomly choosing schematics currently, so that would need to be added. I do see potential in this feature so I'll think about the best way to add this (maybe using something like 'house-*' as schematic name, which will randomly choose one of the schematic files that start with 'house-').

**Comment by NLthijs48** [comment]
I see just now that you want to use this to randomly create city streets, so you don't actually want to use `/as stack` for creating AreaShop regions? Seems like you are using the wrong tool for the job, although it is a very creative solution for your problem.

**Comment by BabelSolea** [comment]
i searching how to do that and tried many plugins)
