### ISSUE TITLE
areashop.schematicevents on own region with out that permission

### ISSUE THREAD

**Issue by BabelSolea** [NLthijs48/AreaShop#310]
How to execute schemevent command by default player but with out: areashop.schematicevents

i need that command to give player thing to clear there own regions.

i did put that in executed command in "info-setRegionTeleport"

so default player owner of region can click it in there own region info.

but that command cant be executed by default player with out "areashop.schematicevents"
so is the way to execute command as OP by default player with out that permission?

**Comment by BabelSolea** [comment]
i want release thats but with default players and only on there own regions.
how to do that?
https://www.youtube.com/watch?v=W-caqVobG7M

**Comment by BabelSolea** [comment]
some way like
executed commands variables:

command - execute command by player
operatorcommand - execute command by player (like if he being a op)
consolecommand - execute command from console

**Comment by NLthijs48** [comment]
I don't think it is a good idea to let them use that command, since that would allow them to reset any region they want. Maybe it is better to configure AreaShop to reset the region when you sell/unrent it, and then creating a command that sells the region and immediately buys it again. You can do this using the [`commands.yml`](http://bukkit.gamepedia.com/Commands.yml) file:
```yaml
aliases:
    resetareashopregion:
    - "areashop sell $$1"
    - "areashop buy $$1"
```
Which will allow you to add `/resetareashopregion %region%` to the output of `areashop info`, as you already tried for the schematic command.

Let me know if that works for you.

**Comment by NLthijs48** [comment]
By the way, the messages you can click to do a command will always be executed as a player, since that is happening in the client of the player. So the only way to allow something to happen with that is simply giving the player a permission.

**Comment by BabelSolea** [comment]
hmm, i have that setup:

+ all regions have different buildings (houses)
+ when player buy region - that lauch save schemevent (with house)
+ when player sell region - that launch restore schemevent (again with house)

+ if player want clear that house and build what he want on cleared plot - he can do that on there own regions in one click

but he cant manage this on other regions where he not owner.

so way to have region with some house by default - help many players to start game with cute little house (and NOT build freaky dirt cages)

but if player want - he also can clear region to build there own idea houses or what he want (or fast clear region if that builded bad idea)

so other players cant edit and click in region info "info-setRegionTeleport" and only owner can (i used that way to change teleport command to schemevent command but found what default players cant do that with out permission AND with permission they can do it on all regions =(

eh =(

**Comment by BabelSolea** [comment]
so players dont using commands - they just manage owned regions by clicking on chat in some string about region info)

**Comment by BabelSolea** [comment]
You can do this using the commands.yml file:

aliases:
    resetareashopregion:
    - "areashop sell $$1"
    - "areashop buy $$1"

dont understand what that do =(

**Comment by NLthijs48** [comment]
Clicking in the chat simply executes a command, so if resetting by command works, then the chat thing will also work. Hiding the message when the player does not have permission will not prevent the player from using the command manually by typing it in the chat.

It looks like you simply need a plugin that does a think like that so you can hook that into the messages sent by AreaShop.

The `commands.yml` thing I described above will not work, because that would place the house again, I did not exactly understand your problem.

**Comment by BabelSolea** [comment]
so would be nice to have schemevent command permission per region like that did with teleports.

can schenevent my own regions
can schemevent all regions

...

**Comment by NLthijs48** [comment]
I really think a permission system like that for using the schemevent command is weird, this was never supposed to be a command that is available for normal players. And a permission system like that is complicated and overkill for this command in my opinion. I think the feature you want can best be implemented in a separate plugin, which can provide a command to use in the AreaShop messages and handle permissions for restoring.

**Comment by NLthijs48** [comment]
Closing this issue, I'm not adding overkill permissions to this command, but maybe I could add a command to let players restore their region if there are more requests for it.
