### ISSUE TITLE
I cant use the Signs!

### ISSUE THREAD

**Issue by mark27205** [NLthijs48/AreaShop#313]
I cant use the signs!

WorldGuard Version: 6.2
WorldEdit: Version 6.1.3

Here is a Video.
https://youtu.be/jul37GYYmxI

**Comment by NLthijs48** [comment]
Can you show me your `config.yml` and `default.yml` file that are in the `/plugins/AreaShop` folder? Maybe something is wrong in the `signProfile` section (in this section the action that should happen when you rightclick a sign is configured).

Maybe you still have the `spawn-protection` setting in the `server.properties` file set to something else than `0`, which could prevent your from clicking signs around spawn. It is not a WorldGuard issue because otherwise there would be a message from it.

**Comment by NLthijs48** [comment]
I assume your problem is fixed
