### ISSUE TITLE
Problem with some Worldguard

### ISSUE THREAD

**Issue by skruidenier** [NLthijs48/AreaShop#316]
#### Current behavior

The plugin can't use some WorldGuard flags as shown in the attached picture
![image](https://cloud.githubusercontent.com/assets/7668514/26363569/b6acff56-3fe1-11e7-8c66-22af91f0ca3d.png)

#### New behavior

It should set these flags in the worldguard region

#### Steps to reproduce (for bugs)

1.  Simply add the flags chest-access-group, build-group and use-group to the AreaShop flagProfiles section in the config.

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.):  Spigot
* Server version: 1.8.8
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.5
* WorldGuard version: 6.2
* Vault version: 1.5.6

#### Your config files (for bugs)

[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/1022806/AreaShop.zip)

**Comment by NLthijs48** [comment]
You need to set the group flags as done [here](https://github.com/NLthijs48/AreaShop/blob/master/AreaShop/src/main/resources/default.yml#L116) in the standard `default.yml` file. The group flags are not handled as separate flags because the WorldGuard command also handles it like this.

The [information block](https://github.com/NLthijs48/AreaShop/blob/master/AreaShop/src/main/resources/default.yml#L100-L107) at the start of the `flagProfile` block explains how you can use the group flags in detail.

Let me know if you figured it out.

**Comment by skruidenier** [comment]
Thanks for your quick reply!
In my case the flagProfile section was in de config.yml instead of default.yml so i decided to remove those files and let the plugin recreate it.
After that i had the correct (2.4.0) files and i followed your information.
Works like a charm!

Thanks and case closed!

**Comment by NLthijs48** [comment]
Yeah you still had the old config layout, that one also still works perfectly though, but the latest one has some more options.

**Comment by skruidenier** [comment]
Maybe an idea to auto update the configs when something changes?
And if it's not possible to copy the data you can save the old configs named as old_config.yml and old_default.yml.

**Comment by NLthijs48** [comment]
Updating old configs is possible, but that would remove all comments in it, so that is the reason I do not want to do that. I always take care that old config files keep working, so that upgrading AreaShop will never break an existing setup. The downside is that you are not really aware of new settings, but of course you can read the changelog to see what is new, or generate a new config like you did.

**Comment by skruidenier** [comment]
True,
Is it an option when i set autoupdate to "false" that i get an in-game message when there's a newer version available?

**Comment by NLthijs48** [comment]
AreaShop does not have an `autoupdate` option, it only has a `checkForUpdates` setting in the `config.yml` file. This will check for updates at each startup and if there is a new version it prints to the console and notifies OP players when they log in to the server.
