### ISSUE TITLE
Crash when selling area

### ISSUE THREAD

**Issue by dejakob1** [NLthijs48/AreaShop#319]
#### Current behavior
When players sell their house the server crashes. This isn't always the case and I'm not sure yet if it the region that's affected or something else.

#### Steps to reproduce (for bugs)
1.  Not exactly sure but it happened 3 times in a row when people sold their area.

#### Your environment (for bugs)
* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.11.2
* AreaShop version: 2.2.0
* WorldEdit version: FAWE 17.6.3-70623d4-708 by Empire92
* WorldGuard version: WorldGuard 6.1.3-SNAPSHOT;c904242
* Vault version: Unknown

#### Your config files (for bugs)
https://www.dropbox.com/s/js9nzxz82rj6drs/areashop.zip?dl=0
Also has a log file with log of crash

**Comment by NLthijs48** [comment]
If you are use FAWE I would not expect it to crash while restoring the region, but I guess that still happens. You could turn of restoring of regions for now to prevent crashes. Also please update AreaShop, WorldEdit and WorldGuard to see if that makes a difference.

If that did not work yet please give me the complete log file of the crash, the part you gave me is just a small part of the crash report and does not have enough information (use the log file in `/logs` instead of the server console).

**Comment by NLthijs48** [comment]
I assume your problem is solved, closing the issue.
