### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by SeussCZ** [NLthijs48/AreaShop#325]
Hi, I have a few errors while compiling. Can u help me, how to fix it please?

https://ctrlv.cz/shots/2017/06/15/GvkQ.png

**Comment by NLthijs48** [comment]
Did you import the AreaShop source as Maven project? Because without it you simply cannot compile it. The WorldGuard6 folder uses WorldGuard 6 to compile and the WorldGuard5 folder uses WorldGuard 5 to compile. Since the method signature of that method changed you cannot compile all sources with one WorldGuard version.

Simply import it as Maven project into Eclipse and you should be able to run `mvn install` directly.

**Comment by SeussCZ** [comment]
With Maven project its the same issue, where I can find missing WorldGuard jars (5, 6) ?

https://dev.bukkit.org/projects/worldguard/files
Which one is corect?

**Comment by NLthijs48** [comment]
I assume your issue is solved, closing the issue.
