### ISSUE TITLE
Wrong formatting and other stuff

### ISSUE THREAD

**Issue by Sandukhan** [NLthijs48/AreaShop#327]
I have been running in some trouble with areashop latly.

First the color formatting in the wiki seems to be wrong, than it comes to [dark_aqua], [dark_green]... the underscore doesnt seems to work. eg:

buy-restrictedToRegion: "You need to be inside [gold]%lang:region%[dark_aqua] to buy it." <-- dosnt work

buy-restrictedToRegion: "You need to be inside [gold]%lang:region%[darkaqua] to buy it." <-- works

Also, areashop seems to have some issues with loading shop signs past server main world, after a server restart. By "main world" i mean the world dedicated in the serverproperties as level-name=Citybuild
Any shop sign inside a diffrent world, cant be proper located:

[08:28:11] [Server thread/WARN]: [AreaShop] Sign with key 0 of region test1 does not have a proper location

However if i set that world into the serverproperties, areashop will locate it signs correctly. Took me some time to figure that out.....

Also, when new players first join a server and bought thier first region, they cant add any other player of that kind to thier plot via /as addfiend. Areashop tells than, that this player had never joint this server before. They need to relog first before areashops get them properly.

Maybe its another past mainworld thing, because the new players firstspawn on our server isnt in the same world as areashop region are....

We are using spigot 1.11 (areashop 2.4.0, worldedit-bukkit-6.1.5, worldguard-6.2), i also tested it in spigot 1.12 (areashop 2.4.0, worldedit-bukkit-6.1.7.2, worldguard-6.2.1) with the same resaults.

**Comment by NLthijs48** [comment]
The color formatting issues should be fixed in the [development builds](http://wiefferink.me:8080/job/AreaShop/), these things have been fixed in [InteractiveMessenger](https://github.com/NLthijs48/InteractiveMessenger) where I have also added a whole bunch of automated tests to prevent this from happening again.

Could you check if the sign problem still happens in the development build? I have changed some loading mechanics so I expect this issue to be solved.

The `/as addfriend` command has also been fixed in the development build, see #297.

And you probably came to the same conclusion, but yes it really is time to release a new AreaShop version 😃.

**Comment by Sandukhan** [comment]
I tested the latest dev build and looks like everything is working fine now with locating the signs. Exept for that a emty/unfinished areashop sign crashes the minecraft client, but i think somebody already mentioned that before.  

I also would recommand a new feature in areashop, for a bit more safty. Im sure you aware of the whole commandblock/ commandsign exploit in mc, that hacker/griefers use to get permissions on a server from inexperienced staffmembers.
They also useing that to get permissions on plots or region, yesterday we had one guy on our server doing that with a commandbook using:

`{"clickEvent":{"action":"run_command","value":"/as addfriend Androboy gs69 "},"hoverEvent":{"action":"show_text","value":{"text":"§2[click]"}},"text":" "}`

I know that, areashop itself cant stop players from creating these books/signs but what i though of was, that you could add a extra notification with a clickevent when somebody is using that kind of command. 
Like: "Are you sure you want to add this Player to your Region? <Yes/No>"
Or: "Are you sure, you want to sell that region? etc..."

That hasnt to be a default thing, but maybe another option in the config file?

Problem is, that these kinds of exploits will be seen a lot in 1.12 thanks to the new toolbar-feature, they dont even have to use a hackclient anymore to do that.
Everyone can now create these Items offline and try use them on a server.

**Comment by NLthijs48** [comment]
> Exept that a emty/unfinished areashop sign crashes the minecraft client
I have no way to reproduce this, how do you get this to happen?

I'm thinking about making it possible to ask for confirmation for all commands, but that would not help at all against exploits like these. The messages in chat where you can click <Yes/No> use commands as well, so that could for example let the client execute `/areashopconfirm addfriend Androboy gs69` to confirm the action. So now the hacker can simply put that command in his book directly to bypass this confirmation. The only way to fix it is by letting the player manually type in a confirmation, which I think is a huge barrier while using AreaShop and should be avoided.

If you have other ideas about stopping this kind of exploit let me know, but currently it looks like there is not really a proper solution. I also think actually using this exploit is a bit hard, players will see a message form AreaShop like `Androboy successfully added as friend to region gs69`, which should be enough for most players to note there is something wrong.

**Comment by Sandukhan** [comment]
Ok i think the problem here is a old/broken lang.yml in areashop. All i did, was puting a sign on a worldguard region that areashop didnt know before and typed [buy] in the first row, leaving rest of the sign blank. This time it also crashed the whole server.

With a diffrent/updated lany.yml that dosent seems to happen anymore.

https://pastebin.com/q2wmaTAK

About the confirmation thing, what you could do is adding a alias feature, so that people could change the whole command inside areashop. Turning the default "/asshopconfirm addfriend" into something else and keep that command hidden from any commandlist.

A alias feature in general would be nice, if you want to allow people further customization with areashop, idk how you feel about that. The only plugin i know, that allows the user to change its commands  is parties.

https://www.spigotmc.org/resources/parties.3709/

However, i agree that it would be a great effort to prevent these kind of exploits via areashop, idk if a gui with clickable items would work diffrent, but i quess not.

**Comment by NLthijs48** [comment]
The exception shows that it happens while saving the region to a schematic file. So probably it is caused by an old WorldEdit/AsyncWorldEdit causing the save to fail. It is still weird that this causes a client crash though, I would never expect that to happen.

> About the confirmation thing, what you could do is adding a alias feature, so that people could change the whole command inside areashop. Turning the default "/asshopconfirm addfriend" into something else and keep that command hidden from any commandlist.

Sadly that is [security through obscurity](https://en.wikipedia.org/wiki/Security_through_obscurity), which is a bad practice and not safe at all. For example after clicking one of the confirmation messages you could simply open your client log files and find out the command your client has send back to the server.

An alias feature to simply change the command is not necessary, [`commands.yml`](http://bukkit.gamepedia.com/Commands.yml) already offers this feature, as well as a lot of plugins that allow you to change any command.

A gui that you need to click to confirm an action would work, you cannot bypass something like that with a command. Still I would not enable this kind of feature by default though, since that would be annoying for players.

**Comment by NLthijs48** [comment]
Since we did not really find a proper solution for the book issue I'll close this issue. If you have a proposal for another solution please tell me.
