### ISSUE TITLE
Players can teleport to unsold houses

### ISSUE THREAD

**Issue by dejakob1** [NLthijs48/AreaShop#328]
Current behavior

Players can do /as tp (name of unsold house)
I don't know how to block this so they can only teleport to their own house. I even tried blocking all permissions but even then they could still do this.

Steps to reproduce (for bugs)

/as tp (name of unsold house)

Your environment (for bugs)

Server platform (Bukkit, Spigot, etc.): Spigot
Server version: 1.11.2
AreaShop version: 2.2.0
WorldEdit version: FAWE 17.6.3-70623d4-708 by Empire92
WorldGuard version: WorldGuard 6.1.3-SNAPSHOT;c904242
Vault version: Unknown
Your config files (for bugs)

https://www.dropbox.com/s/js9nzxz82rj6drs/areashop.zip?dl=0

**Comment by NLthijs48** [comment]
Are you sure you are running AreaShop 2.2.0? Because teleporting to unsold houses was not possible in this version, but has just been added in the development version. You need to remove the `areashop.teleportavailable` and `areashop.teleportavailablesign` permissions to prevent it. 

Make sure you are not testing as OP or as someone with a * permissions, because you can teleport to everything if you have that.

**Comment by NLthijs48** [comment]
I assume your issue has been solved, closing the issue.
