### ISSUE TITLE
Region groups

### ISSUE THREAD

**Issue by Profeer** [NLthijs48/AreaShop#331]
How do i combine regions, For example when player rents region "halli1" it will also rent him region "halli1yla"
I added this into config but it does not rent other areas, it have to rent them separetely

eventCommandProfiles:
  default:
    created:
      before:
      after:
    ##  - "as setowner %player% %region%+"
    deleted:
      before:
      after:
    rented:
      before:
      after:
      - "as setowner %player% %region%yla1"
      - "as setowner %player% %region%yla2"
      - "as setowner %player% %region%yla3"
    extended:
      before:
      after:
    unrented:
      before:
      - "as unrent %region%yla1"
      - "as unrent %region%yla2"
      - "as unrent %region%yla3"
      after:

**Comment by NLthijs48** [comment]
Your config file looks good, assuming the spacing is correct. Did you check the console after renting a region? If the commands fail it should tell that in the console. You can also try setting `debug` in `config.yml` to `true` to get more information in the console about the commands it is executing and if they succeed or not.

If you still cannot figure out the problem, please send me a `.zip` of your `plugins/AreaShop` folder and I'll take a look at your configuration. 

Note that if your sub-regions have a price that is not zero, players can exploit your setup because they get money back when unrenting the sub-regions, while they did not pay anything for them. So make their price zero, take away permission to rent them directly and set `moneyBack` to 0 for them to ensure they get no money when they are unrented.

**Comment by NLthijs48** [comment]
I assume your problem is solved, closing the issue
