### ISSUE TITLE
Server crashes probably in cause of AreaShop

### ISSUE THREAD

**Issue by kikelkik** [NLthijs48/AreaShop#334]
Hey!
A few days ago, the server crashed without any pre-warns and there weren't any commands executed.
Because the error told me to report it to aquifermc.org (paperspigot) I did - but one member suspects AreaShop to be the problem. 
So here's the error-log, I hope that's enough information. If not, please tell me.
https://pastebin.com/qgmPjHXb

#### Steps to reproduce (for bugs)

1. Unfortunately I don't have a clue in which circumstances the server gets crashed.

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): Paper-Spigot #1146
* Server version: 1.12
* AreaShop version: 2.4.0#161
* WorldEdit version: 6.1.8
* WorldGuard version: 6.2.1
* Vault version: 1.5.6

#### Your config files (for bugs)
I dont't think it's relevant information because it just worked very well for months withoud changing any entries.

**Comment by NLthijs48** [comment]
This indeed looks like an infinite loop crash caused by AreaShop, or more specifically the InteractiveMessenger library AreaShop uses. Do you use a custom language file? If you do, could you send that to me? Because most likely you have a broken/different message in there that triggers this problem.

The command this happens is `/as info <region>`, it stalls on displaying the friends that are added to the region. It looks like either the `info-friend` or `info-friendRemove` message in the language file is wrong. It could also be that a player has added a lot of friends, like 1000+ or something like that, maybe you can also check if a region has that (opening `/plugins/AreaShop/regions` and sorting on filesize should work).

**Comment by kikelkik** [comment]
The maximum of friends on a region is 9, a bit less than 1000 :)
Here's my custom language file: https://pastebin.com/AaQQMTJu
There's no 'info-friend' or 'info-friendRemove' . Maybe that's the fault? The language file haven't been changed for plenty of months.

**Comment by NLthijs48** [comment]
I have fixed this issue in the InteractiveMessenger library, I indeed found a case that leads to an infinite loop. There is no development build yet which includes this fix, but I expect to have that within a few days (working a bigger feature which I cannot upload yet).

**Comment by NLthijs48** [comment]
Development build that includes the fix can be found at http://wiefferink.me:8080/job/AreaShop/

**Comment by kikelkik** [comment]
Thanks a lot! :)
