### ISSUE TITLE
Other players can access player shops when I rent one

### ISSUE THREAD

**Issue by Viperfish1** [NLthijs48/AreaShop#336]
#### Current behavior

Exactly what the title says

#### New behavior

Be fixed/Need help

#### Steps to reproduce (for bugs)

1. 
2. 
3. 
4. 

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): 
* Server version: 
* AreaShop version: 
* WorldEdit version: 
* WorldGuard version: 
* Vault version:

**Comment by EvilOlaf** [comment]
Totally missed filling necessary information. 

Therefor invalid.

**Comment by Viperfish1** [comment]
@EvilOlaf 

1. The config seems wrong, since when a player goes to buy a shop, they can! But then, other players can build on it too. Build & Use are allowed in the regions. So is there a way to only let one player be able to have build & use in that region?

**Comment by NLthijs48** [comment]
@Viperfish1 Send me a .zip of your `plugins/AreaShop` folder please, I really need to see you config files to say something useful about this.

The default config files already ensure that only the owner of the region can build there. Since you mention that build and use are allowed in the regions, that would mean you changed it, and 'allow' in WorldGuard means anyone can use it, not only the owner. I advise you to use the config as generated by AreaShop and first test that. Also make sure you are not testing as OP, because you can bypass all region restrictions that way.

**Comment by NLthijs48** [comment]
I assume your problem is solved, closing the issue
