### ISSUE TITLE
Regions not working.

### ISSUE THREAD

**Issue by remibarna** [NLthijs48/AreaShop#350]
#### Current behavior

Hello, 

So I have been having trouble with the flag profiles in default.yml I don't know If im doing something wrong or its the plugin. I have this apartments region and its priority is -1 so It does not interfere with room1 for example. I claimed room1 with worldedit I then defined it. I did /as add rent room1 I added the sign then I went into default and deopped myself to make sure the region works as in the flag profile and it wont let me open doors when Its claimed, **It will allow me to still build and break blocks even when I didnt rent the region** everything is sort of all over the place. 

#### New behavior

The region should make it so you can't break blocks in the region unless you rent it same for opening doors and the dent-message and same for chest-access. When you rent the region you should be able to open doors, break blocks / place blocks and open chests. But when its not rented you should not able to do any of that.

#### Steps to reproduce (for bugs)

1. I did something wrong in config?
2. 
3. 
4. 

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): 
* Server version: 13.08 10:34:12 [Server] INFO This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
13.08 10:34:12 [Server] INFO You are 779 version(s) behind
* AreaShop version: 2.4.0
* WorldEdit version: 5.6.3
* WorldGuard version: 6.1
* Vault version: 1.5.3-b37

#### Your config files (for bugs)

[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/1220505/AreaShop.zip)

**Comment by NLthijs48** [comment]
I cannot find anything obvious that is wrong with your config files. Please send me the output of `/region info` for the region used with AreaShop (room1), the apartments region, any other region at the same location and the `__global__` region.

If you can still break block with the flags as in your config files I think you probably still have some WorldGuard permissions, or are still added to the region, because otherwise this is impossible.

I recommend updating WorldGuard and WorldEdit to the latest versions, you have version 5 of WorldEdit with a version 6 of WorldGuard, this is not really supported correctly. The latest version of both of them still support Spigot 1.8.8, so that should be fine.

Again my apologies for the late reply, I was on holidays.

**Comment by remibarna** [comment]
Well I fixed it. It was the "All" regions section. 

I only wanted it so users rented and be able to open chests and doors and when they didn't rent it wouldn't allow it. So I deleted everything in the region config and only set up the custom "Rented" and "Unrented" parts and now it works. The top part for "All" is what screwed me over for almost 3 days figuring it out.

**Comment by NLthijs48** [comment]
The settings that are in the config when you install AreaShop should be exactly what you need, so I guess you had already changed this section before?

**Comment by remibarna** [comment]
Nope never touched it.
