### ISSUE TITLE
Lag caused by sign spam

### ISSUE THREAD

**Issue by LaughNgamez** [NLthijs48/AreaShop#362]
#### Current behavior
Players spam clicking a sign such as [Sold] can cause lag and drop in server TPS.

#### New behavior
After several clicks it should kick the player or cancel the event.

#### Steps to reproduce (for bugs)

1. Have a sign.
2. Have a reason for players wanting to click the sign such as a good plot expiring soon.
3. Players in anticipation of the plot going up for sale spam the sign.

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.10.2-R0.1 - Spigot-de459a2-51263e9
* AreaShop version: 2.3.2
* WorldEdit version: 6.1.3
* WorldGuard version: 6.2.1
* Vault version: 1.5.6

#### Your config files (for bugs)

[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/1425355/AreaShop.zip)

**Comment by NLthijs48** [comment]
Could you provide timings reports for this problem? (using `/timings` in Spigot) This would make clear if AreaShop or another plugin doing things with signs is causing the lag.

The computation AreaShop does when clicking a sign is very minimal, it only executes the commands as specified in the config. In this case this will trigger the `/as rent` command, which stops quite quickly because the region is already rented. Of course spamming anything on a server might cause lag to some degree, but I don't see a reason why clicking an AreaShop sign would be super expensive.

I see that you are using AreaShop 2.3.2, I at least recommend updating to the 2.4.0 release version, but I don't expect this particular thing to be any different.

**Comment by LaughNgamez** [comment]
It seems you're correct, Areashop just seemed to be the signs used in an unrelated issue.
