### ISSUE TITLE
Question: Region updates?

### ISSUE THREAD

**Issue by Ronnie0982** [NLthijs48/AreaShop#363]
#### Current behavior

Works fine :D

#### New behavior

Is there a feature that updates regions or a config option that you need to change?

**Comment by EvilOlaf** [comment]
What do you mean with "updates regions"? Please explain a little further.

**Comment by NLthijs48** [comment]
Update regions in what sense?
The WorldGuard region flags and signs should update immediately if something changes.

**Comment by Ronnie0982** [comment]
Just a "update" on regions at some times

**Comment by Ronnie0982** [comment]
Like sign/region update over how and how long the player have the region left?

**Comment by NLthijs48** [comment]
@Ronnie0982 Normally the region is never updated, but if you use the `%timeleft%` variable on the sign it will get updated automatically every minute. There are hidden settings to define the interval this happens, but is there any reason you need to change it?

**Comment by Ronnie0982** [comment]
Well it's just that it gets a 0 secs left, and then it never unrents itself after 5 mins...

**Comment by Ronnie0982** [comment]
But maybe it's becuase i have my servers down when the time is over?

**Comment by NLthijs48** [comment]
You should have said that earlier, so your real issue is that rent expiration is not working. Did you change the time modifiers in the config.yml file? Most likely you removed the English modifiers, stopping the task that checks rent expiration. Put [these](https://github.com/NLthijs48/AreaShop/blob/master/AreaShop/src/main/resources/config.yml#L57-L63) back or install the [development build](http://wiefferink.me:8080/job/AreaShop/).

**Comment by Ronnie0982** [comment]
Okay thats why, because i have changed The time modifiers
Ny bad xD

**Comment by Ronnie0982** [comment]
My bad

**Comment by NLthijs48** [comment]
No problem, this is why I fixed this problem for the next version 😄
