### ISSUE TITLE
Crash Error

### ISSUE THREAD

**Issue by SeDark** [NLthijs48/AreaShop#371]
Today my server has stopped and in the log shows traces relative to "AreaShop", that's why I would like to know what problem there is

https://hastebin.com/dayurajiro.md

#### Your environment (for bugs)
* Server version: PaperSpigot 1.12.2
* AreaShop version:  2.4.0#118 (Spigot)
* WorldEdit version: 6.18:3690-11bc229
* WorldGuard version: 6.2.2:1708-3a8e3e8
* Vault version: 1.5.6-b49

#### Your config files (for bugs)
https://hastebin.com/tojuduluva.php

**Comment by NLthijs48** [comment]
This indeed looks like an AreaShop problem. Most likely there is a malformed message in your language file. 

I advise to install the [development build of AreaShop](http://wiefferink.me:8080/job/AreaShop/), which has a lot of improvements in the messaging system that should prevent this from happening again.

If it still happens, please let me know and send me the language file you are using.

**Comment by SeDark** [comment]
For now it seems that it does not happen again, but I have two doubts.

When a user does shift + right click on a rental (shiftRightClickConsole) the sign does not recognize the colors, with any other action it is fixed.

https://i.gyazo.com/43bc65371818973e08a168f9118f2d3c.png
https://i.gyazo.com/dcd6fb927432b6c80554d444a8d4872c.png

And the second question is to know if you could translate the messages of the months (January, February, etc).

**Comment by NLthijs48** [comment]
I have no idea how those signs have broken, could you send your `/plugins/AreaShop` folder again so that I can try to recreate this problem?

Currently you cannot translate the date/time, but it should follow the language of your system. So you could try adding a command line flag like this one to the startup command of your server: `java -Duser.language=es ...`. I have created [a plan](https://github.com/NLthijs48/AreaShop/issues/377) to properly support changing the format.

**Comment by SeDark** [comment]
[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/1593186/AreaShop.zip)

I send you everything, although I do not think you need the schematics

**Comment by NLthijs48** [comment]
For the region of the sign, you have enabled restoring from a schematic file. If the sign is inside the region, it might get broken because it is also updated by the schematic restore. The development build should update the sign again after half a second, but maybe that is too quick. How large is this region? Do you have AsyncWorldEdit/FastAsyncWorldEdit installed?

**Comment by SeDark** [comment]
The sign is not within the schematic region., the schematic load an empty area (to clean the region of blocks inside), it has a size of about 16x16x16.

I use Fastasyncworldedit

**Comment by NLthijs48** [comment]
If the sign is outside of the region the schematic stuff should not matter.

So while the region is rented the sign is fine, but after shift-right clicking on a sign the colors mess up? And the region is not actually unrented yet right? (you would first have to click the chat message). If this happens all the time I would like to check it out, is it possible to join your server? Maybe another plugin is messing something up, because AreaShop does not actually update the sign at all when you click it.

**Comment by SeDark** [comment]
I've been looking for that plugin could be interfering.

And I have come to the conclusion that it is "CMI", since it has a poster editing function, I have modified some permissions and the poster colors are no longer broken.

https://www.spigotmc.org/resources/cmi-ranks-kits-portals-essentials-mysql-sqlite-bungeecord.3742/
