### ISSUE TITLE
Plot signs and chat shows malformed price

### ISSUE THREAD

**Issue by hades200082** [NLthijs48/AreaShop#388]
#### Current behavior
Plot set to price $200 -> Sign shows price as "00"
Plot set to price $20 -> Sign shows price as "0"

The chat window shows the same issue whenever it displays the price too.

#### New behavior
Plot set to price $200 -> Sign shows price as "$200"
Plot set to price $20 -> Sign shows price as "$20"

Chat window should display price correctly too.

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): Spigot 1.12.2
* Server version: 1.12.2
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.7.3
* WorldGuard version: 6.2.1
* Vault version: 1.5.6
* CraftConomy3: 3.3.1

#### Your config files (for bugs)
[areashop.zip](https://github.com/NLthijs48/AreaShop/files/1734129/areashop.zip)

**Comment by NLthijs48** [comment]
I did not manage to replicate your problem on my own server (copied all your settings).
Are you using the release version of AreaShop from Spigot or a development build? If you are using the development build, which version? (`/version AreaShop` shows it exactly)
Note that the price formulas you defined in `default.yml` will only work in the development builds.

Can you show me a screenshot of the sign?
What happens if you set the price to 1234?

**Comment by hades200082** [comment]
oddly It seems to have sorted its self out. I’ve not changed anything in the setup but went on today and it’s displaying properly now.

**Comment by NLthijs48** [comment]
Okey great

One thing that could have caused it is setting the currency prefix to `&`. That would mean you get `&200`, which will get displayed as `00` in the color green, because `&2` is translated to a green color code.

**Comment by hades200082** [comment]
I didn’t have &.

I did try § though. Would that do it?

**Comment by NLthijs48** [comment]
That character does the same thing, the `&` gets translated to the section sign, which the minecraft client uses for color codes. So don't use that symbol :)
