### ISSUE TITLE
Command when a region is bought not being executed

### ISSUE THREAD

**Issue by Dudoleitor** [NLthijs48/AreaShop#406]
When a region is bought or sold no command is executed
The command should be executed.

I've set in default.yml (and tried also in regionName.yml) the command "say %region% has been bought" under eventCommandProfile -> bought -> after (I tried also putting the command under before) but nothing happens. I click the sign keeping the shift key pressed, I click "confirm" in the chat, then I don't own the vault but no command is shown in chat.

Server platform: Spigot
Server version: 1.12
AreaShop version: 2.4.0 (stable) or I've tried with the latest of from the development branch
WorldEdit version: 6.1.8-SNAPSHOT:cd4729f
WorldGuard version: 6.2.1:84bc322
Vault version: 1.6.6

[config.zip](https://github.com/NLthijs48/AreaShop/files/2095965/config.zip)

P.S. as you will see reading the configs, I'm Italian, sorry my English

**Comment by NLthijs48** [comment]
`vault101` is a buy region, but you have added the commands to `unrented`, which will never get triggered for a buy region. So you need to move the commands to the `sold` section.

You did add commands to the `sold` section in default.yml, but because you have an `eventCommandProfile` section in `vault101.yml` these are not used for that region.

**Comment by Dudoleitor** [comment]
Thank you very much, I made so a stupid mistake...
