### ISSUE TITLE
Feature - PlaceholderAPI Support or Ability to grab name of specific Shop Owners. 

### ISSUE THREAD

**Issue by NolanMC** [NLthijs48/AreaShop#408]
Problem: I am currently unsure if this is possible, but I'd like a way to be able to grab player names of owned shops/regions for use in other GUI creation plugins, so that I can make a Teleportation GUI for AreaShops. 

Solution: Limited PlaceholderAPI support where I would be able to grab shop owner names from placeholders like %areashop_owner_regionname% (or something like this). If I use the placeholder %areashop_owner_shop1% and shop1 owner is Notch, then the placeholder would return text saying "Notch".

**Comment by NLthijs48** [comment]
#277 asks for PlaceholderAPI support, so that would include placeholders like the one you suggest. AreaShop already offers options to get this data from another plugins, but of course that requires Java knowledge which is harder than using a couple of placeholders.

Thanks for your suggestions, when implementing placeholder support I'll make sure this is possible.
