### ISSUE TITLE
Error with signs. They're not updating, on reload: rents getting unrented

### ISSUE THREAD

**Issue by Victorschimmell** [NLthijs48/AreaShop#409]
**Current behavior**
I'm running a prison server with Areashop, but the signs won't update (You know the time left). And when i reload the server or restart the server, all rented cells gets unrented.

**Expected behavior**
I think the renting of the regions/cells has an error, but i'm not quiet sure. 

**Steps to reproduce**
1. I don't know..
2. 
3. 
4. 

**Your environment**

* Server platform (Bukkit, Spigot, etc.): 
* Server version: 
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.5:4651611
* WorldGuard version: 6.1.3-SNAPSHOT:c904242
* Vault version: 1.5.6-b49

My config files is right down below..
[Areashop.zip](https://github.com/NLthijs48/AreaShop/files/2142674/Areashop.zip)
[Worldguard.zip](https://github.com/NLthijs48/AreaShop/files/2142675/Worldguard.zip)

**Comment by NLthijs48** [comment]
I'm sorry for the late reply.

The problem is that you have translated the time identifiers like weeks/months/days/hours. This causes the internal timers that unrent regions to stop, because they use the English time identifiers. You can either add back the English ones (you can still add additional ones, just also keep English) or you can install the [development build](http://wiefferink.me:8080/job/AreaShop/).
