### ISSUE TITLE
Price of region %0% changed to %1% per %2%.

### ISSUE THREAD

**Issue by Blackyvk** [NLthijs48/AreaShop#42]
Is the only thing i read when i use    /as setprice 12345 regionname   on any region.

**Comment by NLthijs48** [comment]
In AreaShop V2.2.0 this message changed to the one below, using variable instead of numbered arguments:

> "Price of region %region% changed to %price% per %duration%."

You probably are using a copy of EN.yml with the old message, since the normal EN.yml is getting refreshed on each restart.

To fix your problem you can update your copy of EN.yml, or start using the normal one (if my assumption is true).

I'm moving to messages with variables because this makes it possible for people to use all available variables in custom messages, instead of only the given numbered ones (and it is more clear which thing is getting placed in the message).
