### ISSUE TITLE
Item frames

### ISSUE THREAD

**Issue by x1p** [NLthijs48/AreaShop#470]
**Current behavior**

Item frames don't break when the area rent expires.
Signs however break and dissappear. Item frames including the items in it can be stolen/picked up.
![screenshot_20190101_210749](https://user-images.githubusercontent.com/28690790/50576017-58dec600-0e09-11e9-8f93-0279abd1c67b.png)

**Desired behavior**

Could Item Frames be broken too at expiring/unrenting?

**Your environment**

* Server platform (Bukkit, Spigot, etc.): Paper 1.13.2 build 489
* Server version: 1.13.2
* AreaShop version: dev build 273
* WorldEdit version: v7.0.0-SNAPSHOT;3997-ba8bde0
* WorldGuard version: v7.0.0-SNAPSHOT;1781-cd39387
* Vault version: 1.7.1

**Your config files**

Everything default

**Comment by arizrain1** [comment]
I am having the same issue with item Frames.  All else clears on unrent.
https://gyazo.com/4ec470647e9a739fd6b6d20a8dc79833

Server version: latest 1.13.2
CraftBukkit version git-Spigot-518206a-917411f (MC:1.13.2 (Implementing API version 1.13.2-R0.1-Snapshot)
Worldedit:  7.0.0-beta-04;17f52cb
Worldguard: 7.0.0-beta01;01dfebe
Vault: 1.7.1-b91

**Comment by NLthijs48** [comment]
Because item frames are entities they are untouched when a region gets restored, because that only touches blocks. There is a [long standing issue ](https://github.com/NLthijs48/AreaShop/issues/28) to solve this problem, however it might not be that easy to do this.

Because this has been requested a bunch of times already I'll plan it for the next release, maybe I can find a simple way to at least allow removing item frames when a region gets unrented/sold.

I propose we close this issue as a duplicate, and keep tracking progress in #28 (you can click the 'subscribe' button in the sidebar of that issue to get notifications about it).

PS: sorry for the late reply

**Comment by x1p** [comment]
Ok. Will follow that one
