### ISSUE TITLE
Config.yml not populating

### ISSUE THREAD

**Issue by Salox** [NLthijs48/AreaShop#48]
The Config.yml is not populating when i load/reload as on my server. i have pulled the copy of the yml from github but i don't know if this is the correct set up for the latest version as of 8/14/15

**Comment by NLthijs48** [comment]
First check if AreaShop is starting up correctly, because if one of the dependencies is missing then it will never get to the part that saves the config. To check this you can open the lastest.log file inside your '/logs' folder. If you don't know how to see what is wrong by that file then please provide that file to me and I'll take a look.

**Comment by Salox** [comment]
i'm not sure what log file you needed so i just sent you the one's for that
day. copying the cfg.yml into the non populated file did allow me to use
 AS and so far with out any issue. and as far as i know i'm not missing any
of the dependent plugins. if you can figure out what went wrong that would
be great.

thank you for your time
Salox (Joe)

**Comment by NLthijs48** [comment]
You did not attach or link a file here, did you attach it to the email? Because I don't think that works. If you got to the page of the issue on GitHub then you can drag-and-drop a file to the comment box, that should properly do it.

**Comment by Salox** [comment]
OK I will some time today

**Comment by NLthijs48** [comment]
I'm assuming that you have solved the issue in the meantime, so I will close the issue, if you have not yet solved it and need help then just comment here.
