### ISSUE TITLE
/as find issues with max. price

### ISSUE THREAD

**Issue by EvilOlaf** [NLthijs48/AreaShop#59]
`/as find <buy|rent> [maxprice] [group]`
`maxprice` is an optional argument but not setting a price AreaShop uses 0.0 as `maxprice`. So the list of available shops is pretty short.

v2.2.0

**Comment by NLthijs48** [comment]
There was indeed a couple of problems with `/as find`:
* If you do not specify a maxprice then it would always use a balance of 0.0 (it did not get the players balance correctly).
* Incorrect messages were send to the player when no regions are found (display the message for searching with maxprice instead of the message for searching with balance and the other way around).
* The balance and maxprice variables used in the messages did not use the correct currency layout (only thing they did was rounding).

These things have been fixed in the commit linked above, thanks for your report.
