### ISSUE TITLE
Enhancement: Teleport delay

### ISSUE THREAD

**Issue by EvilOlaf** [NLthijs48/AreaShop#60]
On most servers with PvP enabled you have to use delays before players can teleport themselves to another (and probably safe) location. 

At the moment I have to disable features like `as find` or `as tp` as it would probably be abused to escape a confrontation.

Therefore I suggest to add a configurable time in seconds the player has to wait before any command that would end up in a teleport is executed. The timer should cancel at player movement and player damage.

This could be solved partially by using a 3rd party plugin like MyCommand as well but would be not as nice as a seamless integration.

Thanks for reading.

Best regards
Olaf

**Comment by NLthijs48** [comment]
I know that instant teleportation is a problem for PvP servers, however I don't think that building teleportation delay into AreaShop is a good solution. To make the delay good enough to be usable, it will need a bunch of configuration options, and be quite powerful. However I think that implementing something like that is mostly a waste of time if there are already plugins that can do it (with a lot more options). If all plugins that have commands would implement their own system, then it would also be inconsistent and redundant. For example [BoosCooldowns](http://dev.bukkit.org/bukkit-plugins/booscooldowns/) might be a good plugin to handle these kind of things.

So for now I won't add this to AreaShop, because I don't think it is worth the time (could add something else instead). If you can give good reasons to implement it in AreaShop (for example something that BoosCooldowns cannot do) then of course let me know.

**Comment by EvilOlaf** [comment]
Understandable.
I'll try to realize this by using the MyCommand cooldown which should work fine as well.
