### ISSUE TITLE
Backend with SQL/Flatfile

### ISSUE THREAD

**Issue by ElloElloEllo** [NLthijs48/AreaShop#63]
I know you declined requests for SQL adaption due the marginal improvement at best.
But I would like to propose it again, since there might be some advantages with storing in SQL than seperate region files in a folder:

1. the time it takes for backups to store/recover in the case there is a huge amount of files
2. operations that are not implemented with Areashop but possible with SQL (sorting regions)
3. BungeeCord compability?

**Comment by NLthijs48** [comment]
1. Normally an AreaShop user will likely not even have 1000 regions, so the number of files is not that big. Copying those files for a backup should be very quick to make backups, even on conventional (non-SSD) drives. If you are downloading files by FTP then it is smart to make a .zip beforehand, since that reduces the download time a lot (1 request instead of 1 per file). So I don't see much improvement at all by storing the regions in a database for this point.
2. I don't see why sorting of regions is not possible with the current file storage, I'm actually already sorting the region name output for feedback of a couple commands (I guess you mean that by sorting regions?).
3. This might be a cool thing, but is very complicated to get working. Not only would it require SQL support, it would also need cross-server communication for things like renting/unrenting (to trigger the server into updating region info, signs, fire event commands, trigger schematic save/restores).

Implementing SQL support would basically mean that AreaShop needs to be rewritten almost completely. Instead of current `get information > update information > provide user feedback`, all happening right after each other, it would need to do something like this: `switch to async > get information from storage > wait for information >  update information > switch to sync > provide user feedback`. So implementing something like that for all ways you can interact with AreaShop (commands, signs, etc.) would basically mean that a long time of developing is lost and there would be zero functional changes after it (only SQL support).

So it is still not really going to happen anytime soon, especially because I have limited free time.

**Comment by ElloElloEllo** [comment]
Thanks for the clarification. 

With sorting I meant sorting creating tables sorted by world & type & player, but I realize I can do that to the different yaml files with scripts and regex too.

Thank you again for clearing that up.
