### ISSUE TITLE
Deleting areas

### ISSUE THREAD

**Issue by korhox** [NLthijs48/AreaShop#71]
/as del [region]
will remove flags of the WG region, whuy? One server did lose a lot of flags of spawn-region when we removed AreaShop's renting thing.

**Comment by NLthijs48** [comment]
Removing a region from AreaShop will indeed remove most region flags from the region. The reason I added that is to make sure the greeting messages is gone, since if that would stay then most people would think the region is still linked to AreaShop while it is not.

I agree that this is not an ideal solution, especially not for when you add a region by accident (spawn regions while using '/as add' with a WorldEdit selection). The best thing I can do to minimize this problem would be only removing the greeting/farewell messages, I'll see if I can do that for the next update.
