### ISSUE TITLE
I'm trying to make it so that people can do /home, and get tped to the region they own. Not having to do /as tp {region} just /home. 

### ISSUE THREAD

**Issue by skiingrocks111** [NLthijs48/AreaShop#81]
Indicate the steps you did while encountering the problem, the expected outcome, and the actual outcome. Provide links to your config.yml, default.yml and groups.yml files (use pastebin.com or similar). Also provide a full startup log of your server (this indicates the plugin versions used).

**Comment by NLthijs48** [comment]
Currently you can not easily do this, only with a plugin you could get this to work. There is already a suggestion ticket for adding this to AreaShop, so it might be coming in a future update: #39.

I will close this ticket and mark it as duplicate because the other one already covers this issue, let me know if you have any other questions (you can still comment below).
