### ISSUE TITLE
[Feature Request] Region contents returnable to prior renter upon expiration.

### ISSUE THREAD

**Issue by csorrows** [NLthijs48/AreaShop#85]
When the regions are used as player shops, have the plugin record region contents and chest contents and make it available to the player by command and/or sign. This would make it much safer for shops using plugins like chestshop and the like. The user would not loose building materials and shop contents on expiration.

**Comment by NLthijs48** [comment]
With the [Schematic save/restore functionality](https://github.com/NLthijs48/AreaShop/wiki/Region-blocks-save-restore) that is already in AreaShop you can save a schematic of the region at unrent/sell, and keep it as a backup. Such a backup is however not available directly to the player, so they cannot get it back themselves. An admin would need to move the schematic to the WorldEdit folder and paste it somewhere.

If your player shops all have the same size and direction, then you could also set it up to restore the saved schematic when the player buys/rents a shop again. So that way the player could restore their items themselves by buying a shop again.

There is not really an easy way to make the schematic available to the player after the shop has been sold/unrented, since you would need to paste it somewhere, and deciding where is not easy to determine.

Let me know if one of the above solutions already fixes your problem, or if you have suggestions about what I could do to help implement something better.

**Comment by csorrows** [comment]
I had a discussion with one of the devs of the worldedit project about this exact issue a little while back. What was suggested by him was to check the Id of each block within the region one at a time and if it was a chest, to get the contents then save that all to a flat file.

**Comment by NLthijs48** [comment]
I don't really think that getting the region contents of an unrented/sold region and giving it in item form to the player is a suitable approach. It could help to give players items from chests, but other blocks placed in the region are hard to give back (assume mined normally? assumed mined with silk touch? items with special data (banners)? signs that represent a certain number of items (essentials trade signs)?). So that would get a mess quickly. That is why I was searching for different approaches in my last reply.

As you already commented, #29 might already solve most of the problem by simply preventing the unrent/sell in most cases. Let me know if you have anything other that would be good to add assuming that #29 will be added already (marked it for the v2.3.0 milestone). If #29 is sufficient then I propose that we close this issue.

**Comment by csorrows** [comment]
I agree that what I proposed is pretty complicated and I agree it's probably something that I'm just going to have to code myself. As far as I can see, especially because of the lack of worldedit supporting some entities correctly, #29 would be the best solution as of now.
