### ISSUE TITLE
%timeleft% available in language file

### ISSUE THREAD

**Issue by csorrows** [NLthijs48/AreaShop#86]
Can you make %timeleft% available to 'rent_extended:' in the language file?

**Comment by NLthijs48** [comment]
I'm planning on doing that together with adding the click/hover messages of #18, since changing the source language message will require all languages to update their translation on [Transifex](https://www.transifex.com/evolution-coding/areashop/), and I would like to prevent that happening two times short after each other.

All new messages that I write I'm always making all variables available if that is possible (= have access to a region), however the old messages are not yet all updated, for the reason above and laziness (for every single message I need to lookup all places it is used in the code, add the region to it instead of hard-coded arguments, and then change it in the source language file).
