### ISSUE TITLE
UUID Not working

### ISSUE THREAD

**Issue by leonwilber** [NLthijs48/AreaShop#91]
When a player rents a cell it sets his uuid as a member and thats is not working for some reason: http://puu.sh/l3hvF/23af430112.png

**Comment by NLthijs48** [comment]
Please answer the following questions, that will help me determine where the problem could come from:
* Which kind of server (Bukkit/Spigot/other) are you using? 
* Which version do you use?
* Are you using Bungeecord or another proxy?
* Do you have bungeecord=true in your Spigot settings (if applicable)?
* Do you have your server in online mode or offline mode?
* Which versions of AreaShop and WorldGuard are you using?

**Comment by leonwilber** [comment]
1) Spigot
2) Spigot : 1.8.3
    Area Shop: 2.2.1
3) Yes im using Bungee
4) Yes i have bungeecord=true
5) I have it in offline mode for bungeecord
6) Area Shop: 2.2.1
    World Guard: 6.1

**Comment by NLthijs48** [comment]
Any particular reason you are not using the latest Spigot build? I would at least recommend to update to the latest Spigot (some security fixes have been added since 1.8.3).

Are you sure that the player that has that region still has a player file? You can check if there is a player file with that UUID in your `world/playerdata` folder. This more looks like a worldedit issue to be honest, it does not seem to get the correct name for the UUID.

Do you have this problem with all regions or only for a part of them?
