### ISSUE TITLE
Allowing Groups to what ranks?

### ISSUE THREAD

**Issue by Ironic8b498** [NLthijs48/AreaShop#96]
I have done things many ways in the config.yml file and it still allows players to rent a sign. I have noticed my config file has crazy symbols in it again, but everything seems to be working OK. If I was to update from 2.2.0 to 2.2.1 what changes tn the permission do I have to be aware of?

    groups:
    - -"1stfloorright"
    - -1stfloorleft
    - 2ndfloor
    - "-2ndfloorcorners"

**Comment by NLthijs48** [comment]
I'm not entirely sure what you want to accomplish, do you simply want to prevent any player from buying/renting a region? Or are you trying to make it so that some players can rent/buy a region and others cannot (for example based on their rank)? For the first thing you can use the [permissions](https://github.com/NLthijs48/AreaShop/wiki/Commands-and-Permissions), for the second thing you can use the [limit system](https://github.com/NLthijs48/AreaShop/wiki/Limitgroups-information-and-examples).

I have no idea what kind of config part you have included in your issue, so I'm going to assume that it is irrelevant for now.

Please tell me what exactly is what you want to achieve, then I should be able to give you clear directions.
