### ISSUE TITLE
Command execution failed

### ISSUE THREAD

**Issue by andris155** [NLthijs48/AreaShop#99]
http://pastebin.com/bGmSATmj
Server: Latest Paperspigot 1.8.8
Essentials: Latest dev. EssentialsX (http://ci.drtshock.net/job/essentialsx/)
Vault: Latest 1.5.6

**Comment by NLthijs48** [comment]
It looks like there is a problem in Vault or Essentials that causes this problem, since the depositPlayer() function that is used to give money back to the player that rented the region is getting called over and over. I'm not using EssentialsX and PaperSpigot myself so I don't know if those changed anything about the behaviour of this command.

One thing that helps is executing the command 'as unrent bolt6' yourself instead of letting it happen by clicking the sign, then the stacktrace should give a more clear indication what the cause is for this problem (please post that here again). Currently I cannot do anything more about the problem, there is not something in AreaShop that I can change to fix this.

After taking a look into the Vault sourcecode I found where it is looping ([link](https://github.com/MilkBowl/Vault/blob/master/src/net/milkbowl/vault/economy/plugins/Economy_Essentials.java#L151)) when depositing to a player it cannot find the user (it says it does not exist), then it tries to create the user, and after that indicates the user has been created it tries to deposit to the player again, and then it encounters again that the user does not exist and the story continues. Looks like an Essentials problem to me, maybe check if al the files have correct permissions and that your economy system is working correctly when using its commands (also try to do stuff with non-existing players).

**Comment by NLthijs48** [comment]
I'm assuming the problem has been solved.
